<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_K27IcGKPEe6SUplaisCSHQ" name="MonDiagramme" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_K27IcWKPEe6SUplaisCSHQ" name="Département MSSC">
      <elements xmi:type="process:Lane" xmi:id="_K27IcmKPEe6SUplaisCSHQ" name="Etudiant" actor="_-voTkGKbEe6Gj5K04qXrvQ">
        <elements xmi:type="process:StartEvent" xmi:id="_K27Ic2KPEe6SUplaisCSHQ" name="Démarrer1" outgoing="_K27vjGKPEe6SUplaisCSHQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K27IdGKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K27IdWKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K27IdmKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_K27Id2KPEe6SUplaisCSHQ" name="Remplir le formulaire" outgoing="_2ytY8GKeEe6Gj5K04qXrvQ" incoming="_K27vjGKPEe6SUplaisCSHQ _GtfgAGKyEe6Jdd_cFX0v8A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K27IeGKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K27IeWKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K27IemKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_qG01wGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01wWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01wmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01w2QeEe6w1fQx6ik-6g" name="formulaireInput.prenom" content="formulaireInput?.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01xGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01xWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01xmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01x2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01yGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01yWQeEe6w1fQx6ik-6g" name="formulaireInput.nom" content="formulaireInput?.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01ymQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01y2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01zGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01zWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01zmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01z2QeEe6w1fQx6ik-6g" name="formulaireInput.motifSejour" content="formulaireInput?.motifSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG010GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG010WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMotifSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG010mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0102QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG011GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG011WQeEe6w1fQx6ik-6g" name="formulaireInput.moisRetour" content="formulaireInput?.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG011mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG0112QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG012GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG012WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG012mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0122QeEe6w1fQx6ik-6g" name="formulaireInput.moisDepart" content="formulaireInput?.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG013GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG013WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG015GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG015WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG015mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0152QeEe6w1fQx6ik-6g" name="formulaireInput.mail" content="formulaireInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG016GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG016WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG016mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0162QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG017GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG017WQeEe6w1fQx6ik-6g" name="formulaireInput.specialite" content="formulaireInput?.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG017mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG0172QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG018GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG018WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG018mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0182QeEe6w1fQx6ik-6g" name="formulaireInput.duree" content="formulaireInput?.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG019GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG019WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG019mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0192QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01-GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01-WQeEe6w1fQx6ik-6g" name="formulaireInput.secteurGeographique" content="formulaireInput?.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01-mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01-2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01_GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01_WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01_mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01_2QeEe6w1fQx6ik-6g" name="formulaireInput.paysSejour" content="formulaireInput?.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02AGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02AWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02AmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02A2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02BGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02BWQeEe6w1fQx6ik-6g" name="formulaireInput.villeSejour" content="formulaireInput?.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02BmQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02B2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02CGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02CWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02CmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02C2QeEe6w1fQx6ik-6g" name="formulaireInput.universiteSejour" content="formulaireInput?.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02DGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02DWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02DmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02D2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02EGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02EWQeEe6w1fQx6ik-6g" name="formulaireInput.departementSejour" content="formulaireInput?.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02EmQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02E2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02FGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02FWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02FmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02F2QeEe6w1fQx6ik-6g" name="formulaireInput.specialiteSejour" content="formulaireInput?.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02GGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02GWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_K27Ie2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_K27vgGKPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_K27vgWKPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_K27vgmKPEe6SUplaisCSHQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_K27vg2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_K27vhGKPEe6SUplaisCSHQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_f8EoAGQVEe6LY9FT6NOGNw" name="FormulaireEleve" content="66fd8d94-65b6-46e6-9117-d4712bd07c00" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_K27vhmKPEe6SUplaisCSHQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_qG01sGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" dataReference="formulaire" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01sWQeEe6w1fQx6ik-6g" name="prenom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01smQeEe6w1fQx6ik-6g" name="nom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01s2QeEe6w1fQx6ik-6g" name="motifSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01tGQeEe6w1fQx6ik-6g" name="moisRetour" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01tWQeEe6w1fQx6ik-6g" name="moisDepart" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01t2QeEe6w1fQx6ik-6g" name="mail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01uGQeEe6w1fQx6ik-6g" name="specialite" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01uWQeEe6w1fQx6ik-6g" name="duree" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01umQeEe6w1fQx6ik-6g" name="secteurGeographique" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01u2QeEe6w1fQx6ik-6g" name="paysSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vGQeEe6w1fQx6ik-6g" name="villeSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vWQeEe6w1fQx6ik-6g" name="universiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vmQeEe6w1fQx6ik-6g" name="departementSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01v2QeEe6w1fQx6ik-6g" name="specialiteSejour" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_K27vh2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6YOTgGaCEe6nVstEweJU5Q" name="Formulaire engagement" incoming="_dhJvoGaEEe6nVstEweJU5Q" actor="_-voTkGKbEe6Gj5K04qXrvQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6YOTgWaCEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6YOTgmaCEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6YOTg2aCEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_6YOThGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOThWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOThmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTh2aCEe6nVstEweJU5Q" name="formulaireRIInput.prenom" content="formulaireRIInput?.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTiGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTiWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTimaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTi2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTjGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTjWaCEe6nVstEweJU5Q" name="formulaireRIInput.nom" content="formulaireRIInput?.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTjmaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTj2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTkGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTkWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTkmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTk2aCEe6nVstEweJU5Q" name="formulaireRIInput.moisRetour" content="formulaireRIInput?.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTlGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTlWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTlmaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTl2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTmGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTmWaCEe6nVstEweJU5Q" name="formulaireRIInput.moisDepart" content="formulaireRIInput?.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTmmaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTm2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTnGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTnWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTnmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTn2aCEe6nVstEweJU5Q" name="formulaireRIInput.mail" content="formulaireRIInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOToGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOToWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTomaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTo2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTpGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTpWaCEe6nVstEweJU5Q" name="formulaireRIInput.specialite" content="formulaireRIInput?.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTpmaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTp2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTqGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTqWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTqmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTq2aCEe6nVstEweJU5Q" name="formulaireRIInput.duree" content="formulaireRIInput?.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTrGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTrWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTrmaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTr2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTsGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTsWaCEe6nVstEweJU5Q" name="formulaireRIInput.secteurGeographique" content="formulaireRIInput?.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTsmaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTs2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTtGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTtWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTtmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTt2aCEe6nVstEweJU5Q" name="formulaireRIInput.paysSejour" content="formulaireRIInput?.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTuGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTuWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTumaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTu2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTvGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTvWaCEe6nVstEweJU5Q" name="formulaireRIInput.villeSejour" content="formulaireRIInput?.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTvmaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTv2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTwGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTwWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTwmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTw2aCEe6nVstEweJU5Q" name="formulaireRIInput.universiteSejour" content="formulaireRIInput?.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTxGaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTxWaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTxmaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTx2aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTyGaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTyWaCEe6nVstEweJU5Q" name="formulaireRIInput.departementSejour" content="formulaireRIInput?.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOTymaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOTy2aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOTzGaCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOTzWaCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOTzmaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOTz2aCEe6nVstEweJU5Q" name="formulaireRIInput.specialiteSejour" content="formulaireRIInput?.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOT0GaCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOT0WaCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6YOT0maCEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6YOT02aCEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6YOT1GaCEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6YOT1WaCEe6nVstEweJU5Q" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6YOT1maCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6YOT12aCEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6YOT2GaCEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6YOT2WaCEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6YOT2maCEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6YOT22aCEe6nVstEweJU5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6YOT3GaCEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_6YOT3WaCEe6nVstEweJU5Q" name="Boundary Minuterie1" outgoing="_MIugsGaDEe6nVstEweJU5Q">
            <condition xmi:type="expression:Expression" xmi:id="_6YOT3maCEe6nVstEweJU5Q" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6YOT32aCEe6nVstEweJU5Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_6YOT4GaCEe6nVstEweJU5Q" name="engagement" content="068a7a97-dcd1-42a1-9ac3-684c24e67397" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6YOT4WaCEe6nVstEweJU5Q">
            <inputs xmi:type="process:ContractInput" xmi:id="_6YOT4maCEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT42aCEe6nVstEweJU5Q" name="prenom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT5GaCEe6nVstEweJU5Q" name="nom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT5WaCEe6nVstEweJU5Q" name="moisRetour" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT5maCEe6nVstEweJU5Q" name="moisDepart" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT52aCEe6nVstEweJU5Q" name="mail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT6GaCEe6nVstEweJU5Q" name="specialite" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT6WaCEe6nVstEweJU5Q" name="duree" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT6maCEe6nVstEweJU5Q" name="secteurGeographique" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT62aCEe6nVstEweJU5Q" name="paysSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT7GaCEe6nVstEweJU5Q" name="villeSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT7WaCEe6nVstEweJU5Q" name="universiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT7maCEe6nVstEweJU5Q" name="departementSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT72aCEe6nVstEweJU5Q" name="specialiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_6YOT8GaCEe6nVstEweJU5Q" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6YOT8WaCEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_B2UcwGaDEe6nVstEweJU5Q" name="Refus" incoming="_MIugsGaDEe6nVstEweJU5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_B2VD0GaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_B2UcwWaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_B2VD0WaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_B2VD0maDEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_B2VD02aDEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_B2VD1GaDEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_B2VD1maDEe6nVstEweJU5Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_B2VD1WaDEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_1R6rkGaDEe6nVstEweJU5Q" name="Démarrer3" outgoing="_dhJvoGaEEe6nVstEweJU5Q" event="mess2" incomingMessag="_6tMzEGaEEe6nVstEweJU5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1R7SoWaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1R7SoGaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1R7SomaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvsR0GaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvsR0WaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvsR0maGEe6nVstEweJU5Q" name="mess2Prenom" content="mess2Prenom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvsR02aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvuHAGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvuHAWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvuHAmaGEe6nVstEweJU5Q" name="mess2Nom" content="mess2Nom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvuHA2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvuHBGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvuHBWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvuHBmaGEe6nVstEweJU5Q" name="mess2MotifSejour" content="mess2MotifSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvuHB2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvuuEGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvuuEWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvuuEmaGEe6nVstEweJU5Q" name="mess2MoisRetour" content="mess2MoisRetour" type="MESSAGE_ID_TYPE" returnType="java.time.LocalDate"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvuuE2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvuuFGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvuuFWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvuuFmaGEe6nVstEweJU5Q" name="mess2MoisDepart" content="mess2MoisDepart" type="MESSAGE_ID_TYPE" returnType="java.util.Date"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvuuF2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvuuGGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvuuGWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvuuGmaGEe6nVstEweJU5Q" name="mess2Mail" content="mess2Mail" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvuuG2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvvVIGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvvVIWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvvVImaGEe6nVstEweJU5Q" name="mess2Specialite" content="mess2Specialite" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvvVI2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_Dvv8MGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Dvv8MWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Dvv8MmaGEe6nVstEweJU5Q" name="mess2Duree" content="mess2Duree" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_Dvv8M2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_Dvv8NGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Dvv8NWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Dvv8NmaGEe6nVstEweJU5Q" name="mess2SecteurGeographique" content="mess2SecteurGeographique" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_Dvv8N2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvwjQGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvwjQWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvwjQmaGEe6nVstEweJU5Q" name="mess2PaysSejour" content="mess2PaysSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvwjQ2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvwjRGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvwjRWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvwjRmaGEe6nVstEweJU5Q" name="mess2VilleSejour" content="mess2VilleSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvwjR2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvxKUGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvxKUWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvxKUmaGEe6nVstEweJU5Q" name="mess2UniversiteSejour" content="mess2UniversiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvxKU2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvxKVGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvxKVWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvxKVmaGEe6nVstEweJU5Q" name="mess2DepartementSejour" content="mess2DepartementSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvxKV2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_DvxxYGaGEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DvxxYWaGEe6nVstEweJU5Q"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DvxxYmaGEe6nVstEweJU5Q" name="mess2SpecialiteSejour" content="mess2SpecialiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DvxxY2aGEe6nVstEweJU5Q" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_6_CMQGKaEe6Gj5K04qXrvQ" name="Secrétariat" actor="_VmvOMGKcEe6Gj5K04qXrvQ">
        <elements xmi:type="process:Task" xmi:id="_xlSR0GKeEe6Gj5K04qXrvQ" name="Contrôle des informations" outgoing="_TYdMMGKxEe6Jdd_cFX0v8A" incoming="_2ytY8GKeEe6Gj5K04qXrvQ" actor="_-voTkGKbEe6Gj5K04qXrvQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xlS44WKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xlS44GKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xlS44mKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_q-0YMmQfEe6LY9FT6NOGNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_q-0YM2QfEe6LY9FT6NOGNw" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_q-0YNGQfEe6LY9FT6NOGNw" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_q-0YNWQfEe6LY9FT6NOGNw" name="formulaireInput.accept" content="formulaireInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_q-0YNmQfEe6LY9FT6NOGNw" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_q-0YN2QfEe6LY9FT6NOGNw" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xlS442KeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xlS45GKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xlS45WKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xlS452KeEe6Gj5K04qXrvQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xlS45mKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_ngcg8GQsEe6h_5UvdM1dDg" name="1min" outgoing="_XLQaUGKvEe6Jdd_cFX0v8A">
            <condition xmi:type="expression:Expression" xmi:id="__oCa4GKeEe6Gj5K04qXrvQ" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xlS46WKeEe6Gj5K04qXrvQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_zxnDgGQfEe6LY9FT6NOGNw" name="FormulaireControle" content="df9b8c2f-e776-4c93-9238-81b8c7d1af40" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xlS46GKeEe6Gj5K04qXrvQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_q-0YMGQfEe6LY9FT6NOGNw" name="formulaireInput" type="COMPLEX" dataReference="formulaire" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_q-0YMWQfEe6LY9FT6NOGNw" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xlS462KeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_5cFJwGKwEe6Jdd_cFX0v8A" name="Porte1" outgoing="_GtfgAGKyEe6Jdd_cFX0v8A _GeCTIGQwEe6h_5UvdM1dDg" incoming="_TYdMMGKxEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5cFw0WKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5cFw0GKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5cFw0mKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_P3AwoGKvEe6Jdd_cFX0v8A" name="Traitement avec du retard" outgoing="_jLaZgGKvEe6Jdd_cFX0v8A" incoming="_XLQaUGKvEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_P3HeUWKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_P3HeUGKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_P3HeUmKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_klY9sGQvEe6h_5UvdM1dDg" name="Traitement avec du retard" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_klY9sWQvEe6h_5UvdM1dDg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9smQvEe6h_5UvdM1dDg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_klY9s2QvEe6h_5UvdM1dDg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9tGQvEe6h_5UvdM1dDg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_klY9tWQvEe6h_5UvdM1dDg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9tmQvEe6h_5UvdM1dDg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_klY9t2QvEe6h_5UvdM1dDg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9uGQvEe6h_5UvdM1dDg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_klY9uWQvEe6h_5UvdM1dDg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9umQvEe6h_5UvdM1dDg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_klY9u2QvEe6h_5UvdM1dDg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9vGQvEe6h_5UvdM1dDg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_klY9vWQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9vmQvEe6h_5UvdM1dDg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_klY9v2QvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9wGQvEe6h_5UvdM1dDg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_klY9wWQvEe6h_5UvdM1dDg" name="alexander.duchemin@entreprise.com" content="alexander.duchemin@entreprise.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9wmQvEe6h_5UvdM1dDg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_klY9w2QvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9xGQvEe6h_5UvdM1dDg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_klY9xWQvEe6h_5UvdM1dDg" name="to()" content="formulaire.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.FormObject" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY9xmQvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9x2QvEe6h_5UvdM1dDg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_klY9yGQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9yWQvEe6h_5UvdM1dDg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_klY9ymQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9y2QvEe6h_5UvdM1dDg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_klY9zGQvEe6h_5UvdM1dDg" name="Dossier en cours de traitement" content="Dossier en cours de traitement" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9zWQvEe6h_5UvdM1dDg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_klY9zmQvEe6h_5UvdM1dDg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9z2QvEe6h_5UvdM1dDg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_klY90GQvEe6h_5UvdM1dDg" name="&lt;pattern-expression>" content="&lt;p>&lt;span style=&quot;font-size:12px&quot;>Bonjour ${formulaire.prenom} ${formulaire.nom}&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:12px&quot;>&lt;span style=&quot;font-family:Calibri&quot;>&lt;span style=&quot;font-family:Calibri&quot;>Votre dossier est bien en cours de traitement mais avec du retard.&lt;/span>&lt;/span>&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:12px&quot;>Le secr&amp;eacute;tariat&lt;/span>&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_klY90WQvEe6h_5UvdM1dDg" name="formulaire.prenom" content="formulaire.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_klY90mQvEe6h_5UvdM1dDg" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY902QvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_klY91GQvEe6h_5UvdM1dDg" name="formulaire.nom" content="formulaire.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_klY91WQvEe6h_5UvdM1dDg" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY91mQvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY912QvEe6h_5UvdM1dDg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_klY92GQvEe6h_5UvdM1dDg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY92WQvEe6h_5UvdM1dDg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_klY92mQvEe6h_5UvdM1dDg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY922QvEe6h_5UvdM1dDg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_klY93GQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY93WQvEe6h_5UvdM1dDg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_klY93mQvEe6h_5UvdM1dDg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_P3HeU2KvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_P3HeVGKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_P3HeVWKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_P3IFYWKvEe6Jdd_cFX0v8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_P3IFYGKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fD6_sGKvEe6Jdd_cFX0v8A" name="Fin1" incoming="_jLaZgGKvEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fD7mwWKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fD7mwGKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fD7mwmKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_UApScGZzEe6nVstEweJU5Q" name="Fin5" incoming="_GeCTIGQwEe6h_5UvdM1dDg" outgoingMessages="_bsFlQGQwEe6h_5UvdM1dDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DtooEmQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DtooEWQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DtooE2QwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_bsBT0GQwEe6h_5UvdM1dDg" name="mess">
            <correlation xmi:type="process:Correlation" xmi:id="_bsBT0WQwEe6h_5UvdM1dDg">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_bsBT0mQwEe6h_5UvdM1dDg"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_imqQ4WaEEe6nVstEweJU5Q" name="Relation internationale" content="Relation internationale"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_imqQ4GaEEe6nVstEweJU5Q" name="Démarrer2" content="Démarrer2"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_bsBT1WQwEe6h_5UvdM1dDg">
              <expressions xmi:type="expression:ListExpression" xmi:id="_rfTGgGZ5Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_rfTGgWZ5Ee6nVstEweJU5Q" name="messprenom" content="messprenom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_rfTGgmZ5Ee6nVstEweJU5Q" name="newScript()" content="formulaire.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fTUm8GZ7Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_k8p8EGZ9Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_k8p8EWZ9Ee6nVstEweJU5Q" name="messmoisDepart" content="messmoisDepart" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_k8p8EmZ9Ee6nVstEweJU5Q" name="newScript()" content="formulaire.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rdyGwGZ9Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7AGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7AWZ_Ee6nVstEweJU5Q" name="messNom" content="messNom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7AmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7A2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7BGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7BWZ_Ee6nVstEweJU5Q" name="messmoisRetour" content="messmoisRetour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7BmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7B2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7CGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7CWZ_Ee6nVstEweJU5Q" name="messMotif" content="messMotif" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7CmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.motifSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7C2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7DGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7DWZ_Ee6nVstEweJU5Q" name="messMail" content="messMail" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7DmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7D2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7EGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7EWZ_Ee6nVstEweJU5Q" name="messSpecialite" content="messSpecialite" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7EmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7E2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7FGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7FWZ_Ee6nVstEweJU5Q" name="messDuree" content="messDuree" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7FmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7F2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7GGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7GWZ_Ee6nVstEweJU5Q" name="messSecteurGeographique" content="messSecteurGeographique" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7GmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7G2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7HGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7HWZ_Ee6nVstEweJU5Q" name="messPaysSejour" content="messPaysSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7HmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7H2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7IGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7IWZ_Ee6nVstEweJU5Q" name="messVilleSejour" content="messVilleSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7ImZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7I2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7JGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7JWZ_Ee6nVstEweJU5Q" name="messUniversiteSejour" content="messUniversiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7JmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7J2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7KGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7KWZ_Ee6nVstEweJU5Q" name="messDepartementSejour" content="messDepartementSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7KmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7K2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_0Ft7LGZ_Ee6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7LWZ_Ee6nVstEweJU5Q" name="messSpecialiteSejour" content="messSpecialiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_0Ft7LmZ_Ee6nVstEweJU5Q" name="newScript()" content="formulaire.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0Ft7L2Z_Ee6nVstEweJU5Q" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_QZNXEGQVEe6LY9FT6NOGNw" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject">
        <defaultValue xmi:type="expression:Expression" xmi:id="_QZNXEWQVEe6LY9FT6NOGNw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_K27viGKPEe6SUplaisCSHQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_L2zNwGaEEe6nVstEweJU5Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_K27vimKPEe6SUplaisCSHQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_K27vi2KPEe6SUplaisCSHQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K27vjGKPEe6SUplaisCSHQ" target="_K27Id2KPEe6SUplaisCSHQ" source="_K27Ic2KPEe6SUplaisCSHQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K27vjWKPEe6SUplaisCSHQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_K27vjmKPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2ytY8GKeEe6Gj5K04qXrvQ" target="_xlSR0GKeEe6Gj5K04qXrvQ" source="_K27Id2KPEe6SUplaisCSHQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2yuAAGKeEe6Gj5K04qXrvQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2yuAAWKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XLQaUGKvEe6Jdd_cFX0v8A" target="_P3AwoGKvEe6Jdd_cFX0v8A" source="_ngcg8GQsEe6h_5UvdM1dDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XLRBYGKvEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_XLRBYWKvEe6Jdd_cFX0v8A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jLaZgGKvEe6Jdd_cFX0v8A" target="_fD6_sGKvEe6Jdd_cFX0v8A" source="_P3AwoGKvEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jLbAkGKvEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_jLbAkWKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TYdMMGKxEe6Jdd_cFX0v8A" target="_5cFJwGKwEe6Jdd_cFX0v8A" source="_xlSR0GKeEe6Gj5K04qXrvQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TYdMMWKxEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_TYdMMmKxEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GtfgAGKyEe6Jdd_cFX0v8A" target="_K27Id2KPEe6SUplaisCSHQ" source="_5cFJwGKwEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GtgHEGKyEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_GtgHEWKyEe6Jdd_cFX0v8A" name="!isAccept" content="formulaire.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_H5p8kGQwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GeCTIGQwEe6h_5UvdM1dDg" target="_UApScGZzEe6nVstEweJU5Q" source="_5cFJwGKwEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GeC6MGQwEe6h_5UvdM1dDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_GeC6MWQwEe6h_5UvdM1dDg" name="isAccept" content="formulaire.accept==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Nk5-cGRMEe6RotombNdUsw" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MIugsGaDEe6nVstEweJU5Q" target="_B2UcwGaDEe6nVstEweJU5Q" source="_6YOT3WaCEe6nVstEweJU5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MIugsWaDEe6nVstEweJU5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_MIugsmaDEe6nVstEweJU5Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dhJvoGaEEe6nVstEweJU5Q" target="_6YOTgGaCEe6nVstEweJU5Q" source="_1R6rkGaDEe6nVstEweJU5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dhJvoWaEEe6nVstEweJU5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_dhKWsGaEEe6nVstEweJU5Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_-voTkGKbEe6Gj5K04qXrvQ" name="Etudiant" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_VmvOMGKcEe6Gj5K04qXrvQ" name="Secrétaire"/>
      <contract xmi:type="process:Contract" xmi:id="_K27vkGKPEe6SUplaisCSHQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vkWKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vkmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vk2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vlGKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vlWKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vlmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vl2KPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vmGKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vmWKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vmmKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vm2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vnGKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vnWKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vnmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vn2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_7c8QQGKaEe6Gj5K04qXrvQ" name="Relation internationale">
      <elements xmi:type="process:Lane" xmi:id="_8ExFQGKaEe6Gj5K04qXrvQ" name="Management" actor="_RBnyYGRLEe6RotombNdUsw">
        <elements xmi:type="process:Task" xmi:id="_deYzAGK0Ee6hcJAWPaGpNw" name="Contrôle les informations" outgoing="_kOzW4GK0Ee6hcJAWPaGpNw" incoming="_Sj8VAGQwEe6h_5UvdM1dDg" actor="_RBnyYGRLEe6RotombNdUsw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_deb2UWK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_deb2UGK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_deb2UmK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_gJrukmZ4Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gJruk2Z4Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gJrulGZ4Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gJrulWZ4Ee6nVstEweJU5Q" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gJrulmZ4Ee6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gJrul2Z4Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_deb2U2K0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_deb2VGK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_deb2VWK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_deb2V2K0Ee6hcJAWPaGpNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_deb2VmK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_deb2WWK0Ee6hcJAWPaGpNw">
            <targetForm xmi:type="expression:Expression" xmi:id="__Bl6QGQwEe6h_5UvdM1dDg" name="verificationSejour" content="178f7025-628a-4e28-9d16-ceba1bece9e4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_deb2WGK0Ee6hcJAWPaGpNw">
            <inputs xmi:type="process:ContractInput" xmi:id="_gJrukGZ4Ee6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI">
              <inputs xmi:type="process:ContractInput" xmi:id="_gJrukWZ4Ee6nVstEweJU5Q" name="accept" type="BOOLEAN"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_deb2W2K0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_p06q0GK0Ee6hcJAWPaGpNw" name="Fin3" incoming="_rjK_QGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_p07R4WK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_p07R4GK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_p07R4mK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_A0eW0GK1Ee6hcJAWPaGpNw" name="Vérifier dossier scolaire" outgoing="_JKcjQGK1Ee6hcJAWPaGpNw" incoming="_FskuMGK1Ee6hcJAWPaGpNw" actor="_RBnyYGRLEe6RotombNdUsw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A0e94WK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A0e94GK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A0e94mK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_TcVjImaBEe6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_TcVjI2aBEe6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TcVjJGaBEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_TcVjJWaBEe6nVstEweJU5Q" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_TcVjJmaBEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_TcVjJ2aBEe6nVstEweJU5Q" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A0e942K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A0e95GK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A0e95WK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A0e952K1Ee6hcJAWPaGpNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A0e95mK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_A0e96WK1Ee6hcJAWPaGpNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_bvJY8GQzEe6h_5UvdM1dDg" name="verificationDossier" content="af0ea0be-e3b9-4ed3-81f4-d59b94d5daed" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_A0e96GK1Ee6hcJAWPaGpNw">
            <inputs xmi:type="process:ContractInput" xmi:id="_TcVjIGaBEe6nVstEweJU5Q" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI">
              <inputs xmi:type="process:ContractInput" xmi:id="_TcVjIWaBEe6nVstEweJU5Q" name="accept" type="BOOLEAN"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_A0e962K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_HNWkcGK1Ee6hcJAWPaGpNw" name="Porte3" outgoing="_xH9dgGQbEe6w1fQx6ik-6g _7gTgcGaDEe6nVstEweJU5Q" incoming="_JKcjQGK1Ee6hcJAWPaGpNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HNXLgWK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HNXLgGK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HNXLgmK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_No9V8GK1Ee6hcJAWPaGpNw" name="Fin4" incoming="_xuTEwGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_No9V8mK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_No9V8WK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_No9V82K1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_o9SiIGQbEe6w1fQx6ik-6g" name="Rejet formulaire" outgoing="_rjK_QGQbEe6w1fQx6ik-6g" incoming="_q4jU8GQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_o9SiImQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_o9SiIWQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_o9SiI2QbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_o9SiJGQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_o9SiJWQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_o9SiJmQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_o9SiKGQbEe6w1fQx6ik-6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_o9SiJ2QbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_sgmQ0GQbEe6w1fQx6ik-6g" name="Rejet dossier scolaire" outgoing="_xuTEwGQbEe6w1fQx6ik-6g" incoming="_xH9dgGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sgm34WQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sgm34GQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sgm34mQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sgm342QbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sgm35GQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sgm35WQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sgm352QbEe6w1fQx6ik-6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sgm35mQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_SmJDUGZzEe6nVstEweJU5Q" name="Démarrer2" outgoing="_Sj8VAGQwEe6h_5UvdM1dDg" event="mess" incomingMessag="_bsFlQGQwEe6h_5UvdM1dDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RzOpwmQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RzOpwWQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RzOpw2QwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_D5VQoGZzEe6nVstEweJU5Q"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_1oeHMGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1oeHMWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3TCyoGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1oeHMmZ_Ee6nVstEweJU5Q" name="messprenom" content="messprenom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1oeHM2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1oeuQGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1oeuQWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3lvFIGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1oeuQmZ_Ee6nVstEweJU5Q" name="messmoisDepart" content="messmoisDepart" type="MESSAGE_ID_TYPE" returnType="java.time.LocalDate"/>
            <operator xmi:type="expression:Operator" xmi:id="_1oeuQ2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1of8YGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1of8YWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_34K48GZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1of8YmZ_Ee6nVstEweJU5Q" name="messNom" content="messNom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1of8Y2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1ogjcGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1ogjcWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4GoLsGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1ogjcmZ_Ee6nVstEweJU5Q" name="messmoisRetour" content="messmoisRetour" type="MESSAGE_ID_TYPE" returnType="java.time.LocalDate"/>
            <operator xmi:type="expression:Operator" xmi:id="_1ogjc2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1ohxkGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1ohxkWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4YEhAGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1ohxkmZ_Ee6nVstEweJU5Q" name="messMotif" content="messMotif" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1ohxk2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setMotifSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1oiYoGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1oiYoWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4wPwcGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1oiYomZ_Ee6nVstEweJU5Q" name="messMail" content="messMail" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1oiYo2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1oi_sGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1oi_sWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_5GdRAGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1oi_smZ_Ee6nVstEweJU5Q" name="messSpecialite" content="messSpecialite" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1oi_s2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1okN0GZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1okN0WZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_5Z048GZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1okN0mZ_Ee6nVstEweJU5Q" name="messDuree" content="messDuree" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1okN02Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1ok04GZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1ok04WZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_5sL0QGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1ok04mZ_Ee6nVstEweJU5Q" name="messSecteurGeographique" content="messSecteurGeographique" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1ok042Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1olb8GZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1olb8WZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6FzOIGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1olb8mZ_Ee6nVstEweJU5Q" name="messPaysSejour" content="messPaysSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1olb82Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1omDAGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1omqEGZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6eCH8GZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1omqEWZ_Ee6nVstEweJU5Q" name="messVilleSejour" content="messVilleSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1omqEmZ_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1onRIGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1onRIWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_7DYQsGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1onRImZ_Ee6nVstEweJU5Q" name="messUniversiteSejour" content="messUniversiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1onRI2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1on4MGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1on4MWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_7bOwAGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1on4MmZ_Ee6nVstEweJU5Q" name="messDepartementSejour" content="messDepartementSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1on4M2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_1on4NGZ_Ee6nVstEweJU5Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1on4NWZ_Ee6nVstEweJU5Q" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormRIObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_733BoGZ_Ee6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1on4NmZ_Ee6nVstEweJU5Q" name="messSpecialiteSejour" content="messSpecialiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_1on4N2Z_Ee6nVstEweJU5Q" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_rFvdYGaBEe6nVstEweJU5Q" name="Porte2" outgoing="_FskuMGK1Ee6hcJAWPaGpNw _q4jU8GQbEe6w1fQx6ik-6g" incoming="_kOzW4GK0Ee6hcJAWPaGpNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jM5N8WK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jM5N8GK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jM5N8mK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_y6-pYGaDEe6nVstEweJU5Q" name="Fin6" incoming="_7gTgcGaDEe6nVstEweJU5Q" outgoingMessages="_6tMzEGaEEe6nVstEweJU5Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y6_QcWaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y6_QcGaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y6_QcmaDEe6nVstEweJU5Q" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_6tLk8GaEEe6nVstEweJU5Q" name="mess2">
            <correlation xmi:type="process:Correlation" xmi:id="_6tLk8WaEEe6nVstEweJU5Q">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_6tLk8maEEe6nVstEweJU5Q"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_6tLk82aEEe6nVstEweJU5Q" name="Département MSSC" content="Département MSSC" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_6tLk9GaEEe6nVstEweJU5Q" name="Démarrer3" content="Démarrer3" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_6tLk9WaEEe6nVstEweJU5Q">
              <expressions xmi:type="expression:ListExpression" xmi:id="_6tLk9maEEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_6tLk92aEEe6nVstEweJU5Q" name="mess2Prenom" content="mess2Prenom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_6tLk-GaEEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6tLk-WaEEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_6tLk-maEEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_6tLk-2aEEe6nVstEweJU5Q" name="mess2Nom" content="mess2Nom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_6tLk_GaEEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6tLk_WaEEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_6tLk_maEEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_6tLk_2aEEe6nVstEweJU5Q" name="mess2MotifSejour" content="mess2MotifSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_6tLlAGaEEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.motifSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6tLlAWaEEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_6tLlAmaEEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_6tLlA2aEEe6nVstEweJU5Q" name="mess2MoisRetour" content="mess2MoisRetour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_6tLlBGaEEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6tLlBWaEEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tur4wGaFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf0GaFEe6nVstEweJU5Q" name="mess2MoisDepart" content="mess2MoisDepart" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf0WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf0maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf02aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf1GaFEe6nVstEweJU5Q" name="mess2Mail" content="mess2Mail" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf1WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf1maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf12aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf2GaFEe6nVstEweJU5Q" name="mess2Specialite" content="mess2Specialite" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf2WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf2maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf22aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf3GaFEe6nVstEweJU5Q" name="mess2Duree" content="mess2Duree" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf3WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf3maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf32aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf4GaFEe6nVstEweJU5Q" name="mess2SecteurGeographique" content="mess2SecteurGeographique" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf4WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf4maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf42aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf5GaFEe6nVstEweJU5Q" name="mess2PaysSejour" content="mess2PaysSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf5WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf5maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf52aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf6GaFEe6nVstEweJU5Q" name="mess2VilleSejour" content="mess2VilleSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf6WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf6maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf62aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf7GaFEe6nVstEweJU5Q" name="mess2UniversiteSejour" content="mess2UniversiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf7WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf7maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf72aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf8GaFEe6nVstEweJU5Q" name="mess2DepartementSejour" content="mess2DepartementSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf8WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf8maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_tusf82aFEe6nVstEweJU5Q">
                <expressions xmi:type="expression:Expression" xmi:id="_tusf9GaFEe6nVstEweJU5Q" name="mess2SpecialiteSejour" content="mess2SpecialiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_tusf9WaFEe6nVstEweJU5Q" name="newScript()" content="formulaireRI.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tusf9maFEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_8XGycGKaEe6Gj5K04qXrvQ" name="Comptabilité" actor="_UZC2kGKdEe6Gj5K04qXrvQ"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_evG_cGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Lr_mkGZxEe6nVstEweJU5Q" name="" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_7e-3r2KaEe6Gj5K04qXrvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_L6CH8GaEEe6nVstEweJU5Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_7e-3sWKaEe6Gj5K04qXrvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_7e-3smKaEe6Gj5K04qXrvQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kOzW4GK0Ee6hcJAWPaGpNw" target="_rFvdYGaBEe6nVstEweJU5Q" source="_deYzAGK0Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kOz98GK0Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kOz98WK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FskuMGK1Ee6hcJAWPaGpNw" target="_A0eW0GK1Ee6hcJAWPaGpNw" source="_rFvdYGaBEe6nVstEweJU5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FskuMWK1Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_FskuMmK1Ee6hcJAWPaGpNw" name="isAccept" content="formulaireRI.accept==true&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u-mlUGaBEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JKcjQGK1Ee6hcJAWPaGpNw" target="_HNWkcGK1Ee6hcJAWPaGpNw" source="_A0eW0GK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JKcjQWK1Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_JKcjQmK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q4jU8GQbEe6w1fQx6ik-6g" target="_o9SiIGQbEe6w1fQx6ik-6g" source="_rFvdYGaBEe6nVstEweJU5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q4jU8WQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_q4jU8mQbEe6w1fQx6ik-6g" name="!isAccept" content="formulaireRI.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S-T1cGQzEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rjK_QGQbEe6w1fQx6ik-6g" target="_p06q0GK0Ee6hcJAWPaGpNw" source="_o9SiIGQbEe6w1fQx6ik-6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rjLmUGQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_rjLmUWQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xH9dgGQbEe6w1fQx6ik-6g" target="_sgmQ0GQbEe6w1fQx6ik-6g" source="_HNWkcGK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xH9dgWQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_xH9dgmQbEe6w1fQx6ik-6g" name="!isAccept" content="formulaireRI.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S1PbMGRCEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xuTEwGQbEe6w1fQx6ik-6g" target="_No9V8GK1Ee6hcJAWPaGpNw" source="_sgmQ0GQbEe6w1fQx6ik-6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xuTEwWQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_xuTEwmQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sj8VAGQwEe6h_5UvdM1dDg" target="_deYzAGK0Ee6hcJAWPaGpNw" source="_SmJDUGZzEe6nVstEweJU5Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sj8VAWQwEe6h_5UvdM1dDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sj8VAmQwEe6h_5UvdM1dDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7gTgcGaDEe6nVstEweJU5Q" target="_y6-pYGaDEe6nVstEweJU5Q" source="_HNWkcGK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7gTgcWaDEe6nVstEweJU5Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_7gTgcmaDEe6nVstEweJU5Q" name="isAccept" content="formulaireRI.accept==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CFLisGaEEe6nVstEweJU5Q" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormRIObject"/>
        </condition>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_oAWCwGKcEe6Gj5K04qXrvQ" name="Directeur"/>
      <actors xmi:type="process:Actor" xmi:id="_UZC2kGKdEe6Gj5K04qXrvQ" name="Comptable"/>
      <actors xmi:type="process:Actor" xmi:id="_RBnyYGRLEe6RotombNdUsw" name="Etudiant"/>
      <contract xmi:type="process:Contract" xmi:id="_7e-3s2KaEe6Gj5K04qXrvQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3oGKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3oWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3omKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3o2KaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3pGKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3pWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3pmKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3p2KaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3qGKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3qWKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3qmKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3q2KaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3rGKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3rWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3rmKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_K27voGKPEe6SUplaisCSHQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_K27voWKPEe6SUplaisCSHQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_K27vomKPEe6SUplaisCSHQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_K27vo2KPEe6SUplaisCSHQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_K27vpGKPEe6SUplaisCSHQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_K27vpWKPEe6SUplaisCSHQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_K27vpmKPEe6SUplaisCSHQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_K27vp2KPEe6SUplaisCSHQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_K27vqGKPEe6SUplaisCSHQ" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_bsFlQGQwEe6h_5UvdM1dDg" name="mess" target="_SmJDUGZzEe6nVstEweJU5Q" source="_UApScGZzEe6nVstEweJU5Q"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_6tMzEGaEEe6nVstEweJU5Q" name="mess2" target="_1R6rkGaDEe6nVstEweJU5Q" source="_y6-pYGaDEe6nVstEweJU5Q"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_K27vqWKPEe6SUplaisCSHQ" type="Process" element="_K27IcGKPEe6SUplaisCSHQ" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_K27vqmKPEe6SUplaisCSHQ" type="2007" element="_K27IcWKPEe6SUplaisCSHQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vq2KPEe6SUplaisCSHQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vrGKPEe6SUplaisCSHQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_K27vrWKPEe6SUplaisCSHQ" type="3007" element="_K27IcmKPEe6SUplaisCSHQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_K27vrmKPEe6SUplaisCSHQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_K27vr2KPEe6SUplaisCSHQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_K27vsGKPEe6SUplaisCSHQ" type="3005" element="_K27Id2KPEe6SUplaisCSHQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_K27vsWKPEe6SUplaisCSHQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vsmKPEe6SUplaisCSHQ" x="232" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K27vs2KPEe6SUplaisCSHQ" type="3002" element="_K27Ic2KPEe6SUplaisCSHQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_K27vtGKPEe6SUplaisCSHQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_K27vtWKPEe6SUplaisCSHQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vtmKPEe6SUplaisCSHQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6YO6kGaCEe6nVstEweJU5Q" type="3005" element="_6YOTgGaCEe6nVstEweJU5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6YO6kWaCEe6nVstEweJU5Q" type="5005" element="_6YOTgGaCEe6nVstEweJU5Q"/>
              <children xmi:type="notation:Shape" xmi:id="_6YO6l2aCEe6nVstEweJU5Q" type="3043" element="_6YOT3WaCEe6nVstEweJU5Q" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_6YO6mGaCEe6nVstEweJU5Q" type="5055" element="_6YOT3WaCEe6nVstEweJU5Q">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_6YO6mWaCEe6nVstEweJU5Q" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6YO6mmaCEe6nVstEweJU5Q" x="24" y="58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6YO6lmaCEe6nVstEweJU5Q" x="641" y="56" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B2Vq4GaDEe6nVstEweJU5Q" type="3027" element="_B2UcwGaDEe6nVstEweJU5Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_B2Vq4maDEe6nVstEweJU5Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B2Vq4WaDEe6nVstEweJU5Q" x="758" y="233"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1R7So2aDEe6nVstEweJU5Q" type="3012" element="_1R6rkGaDEe6nVstEweJU5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1R7SpWaDEe6nVstEweJU5Q" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1R7SpmaDEe6nVstEweJU5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1R7SpGaDEe6nVstEweJU5Q" x="565" y="75"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_K27vt2KPEe6SUplaisCSHQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_K27vuGKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_K27vuWKPEe6SUplaisCSHQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_K27vumKPEe6SUplaisCSHQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vu2KPEe6SUplaisCSHQ" x="28" y="10" width="1604" height="486"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_6_OZgGKaEe6Gj5K04qXrvQ" type="3007" element="_6_CMQGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_6_PAkGKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6_PAkWKaEe6Gj5K04qXrvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xlUHAGKeEe6Gj5K04qXrvQ" type="3005" element="_xlSR0GKeEe6Gj5K04qXrvQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xlUHAmKeEe6Gj5K04qXrvQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_ngdIAGQsEe6h_5UvdM1dDg" type="3064" element="_ngcg8GQsEe6h_5UvdM1dDg" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_ngdvEGQsEe6h_5UvdM1dDg" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_ngdvEWQsEe6h_5UvdM1dDg" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ngdIAWQsEe6h_5UvdM1dDg"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xlUHAWKeEe6Gj5K04qXrvQ" x="214" y="56" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5cGX4GKwEe6Jdd_cFX0v8A" type="3008" element="_5cFJwGKwEe6Jdd_cFX0v8A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5cGX4mKwEe6Jdd_cFX0v8A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5cGX42KwEe6Jdd_cFX0v8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5cGX4WKwEe6Jdd_cFX0v8A" x="416" y="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P3R2YGKvEe6Jdd_cFX0v8A" type="3027" element="_P3AwoGKvEe6Jdd_cFX0v8A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P3SdcGKvEe6Jdd_cFX0v8A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P3R2YWKvEe6Jdd_cFX0v8A" x="369" y="221" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fD7mw2KvEe6Jdd_cFX0v8A" type="3003" element="_fD6_sGKvEe6Jdd_cFX0v8A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fD7mxWKvEe6Jdd_cFX0v8A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fD7mxmKvEe6Jdd_cFX0v8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fD7mxGKvEe6Jdd_cFX0v8A" x="612" y="241"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UAp5gGZzEe6nVstEweJU5Q" type="3011" element="_UApScGZzEe6nVstEweJU5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UAp5gmZzEe6nVstEweJU5Q" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UAp5g2ZzEe6nVstEweJU5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UAp5gWZzEe6nVstEweJU5Q" x="542" y="80" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6_OZgWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6_OZgmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6_OZg2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6_PAkmKaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6_OZhGKaEe6Gj5K04qXrvQ" x="53" y="180" width="1292" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_K27vvGKPEe6SUplaisCSHQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_K27vvWKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_K27vvmKPEe6SUplaisCSHQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_K27vv2KPEe6SUplaisCSHQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vwGKPEe6SUplaisCSHQ" width="1632" height="539"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_7fAFwGKaEe6Gj5K04qXrvQ" type="2007" element="_7c8QQGKaEe6Gj5K04qXrvQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_7fAs0GKaEe6Gj5K04qXrvQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_7fAs0WKaEe6Gj5K04qXrvQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_8EyTYGKaEe6Gj5K04qXrvQ" type="3007" element="_8ExFQGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_8EyTZWKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8EyTZmKaEe6Gj5K04qXrvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_delAQGK0Ee6hcJAWPaGpNw" type="3005" element="_deYzAGK0Ee6hcJAWPaGpNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_delAQmK0Ee6hcJAWPaGpNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_delAQWK0Ee6hcJAWPaGpNw" x="178" y="44" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_p0748GK0Ee6hcJAWPaGpNw" type="3003" element="_p06q0GK0Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_p0748mK0Ee6hcJAWPaGpNw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_p07482K0Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p0748WK0Ee6hcJAWPaGpNw" x="662" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A0fk8GK1Ee6hcJAWPaGpNw" type="3005" element="_A0eW0GK1Ee6hcJAWPaGpNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_A0fk8mK1Ee6hcJAWPaGpNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A0fk8WK1Ee6hcJAWPaGpNw" x="323" y="162" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HNXLg2K1Ee6hcJAWPaGpNw" type="3008" element="_HNWkcGK1Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HNXLhWK1Ee6hcJAWPaGpNw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HNXykGK1Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HNXLhGK1Ee6hcJAWPaGpNw" x="522" y="177"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_No99AGK1Ee6hcJAWPaGpNw" type="3003" element="_No9V8GK1Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_No99AmK1Ee6hcJAWPaGpNw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_No99A2K1Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_No99AWK1Ee6hcJAWPaGpNw" x="758" y="184"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o9TJMGQbEe6w1fQx6ik-6g" type="3027" element="_o9SiIGQbEe6w1fQx6ik-6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o9TJMmQbEe6w1fQx6ik-6g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o9TJMWQbEe6w1fQx6ik-6g" x="458" y="56" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sgne8GQbEe6w1fQx6ik-6g" type="3027" element="_sgmQ0GQbEe6w1fQx6ik-6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sgne8mQbEe6w1fQx6ik-6g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sgne8WQbEe6w1fQx6ik-6g" x="593" y="164" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SmLfkGZzEe6nVstEweJU5Q" type="3012" element="_SmJDUGZzEe6nVstEweJU5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SmLfkmZzEe6nVstEweJU5Q" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SmLfk2ZzEe6nVstEweJU5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SmLfkWZzEe6nVstEweJU5Q" x="62" y="66" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rFvdZGaBEe6nVstEweJU5Q" type="3008" element="_rFvdYGaBEe6nVstEweJU5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rFvdZmaBEe6nVstEweJU5Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rFwEcGaBEe6nVstEweJU5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rFvdZWaBEe6nVstEweJU5Q" x="374" y="59" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y6_3gGaDEe6nVstEweJU5Q" type="3011" element="_y6-pYGaDEe6nVstEweJU5Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_y6_3gmaDEe6nVstEweJU5Q" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_y6_3g2aDEe6nVstEweJU5Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y6_3gWaDEe6nVstEweJU5Q" x="631" y="312"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8EyTYWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8EyTYmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8EyTY2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8EyTZ2KaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8EyTZGKaEe6Gj5K04qXrvQ" x="53" y="10" width="1292" height="581"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_8XHZgGKaEe6Gj5K04qXrvQ" type="3007" element="_8XGycGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_8XHZhWKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8XHZhmKaEe6Gj5K04qXrvQ" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8XHZgWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8XHZgmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8XHZg2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8XIAkGKaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8XHZhGKaEe6Gj5K04qXrvQ" x="257" y="179"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_7fAFwWKaEe6Gj5K04qXrvQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_7fAFwmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_7fAFw2KaEe6Gj5K04qXrvQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_7fAs0mKaEe6Gj5K04qXrvQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7fAFxGKaEe6Gj5K04qXrvQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_K27vwWKPEe6SUplaisCSHQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_K27vwmKPEe6SUplaisCSHQ" type="4001" element="_K27vjGKPEe6SUplaisCSHQ" source="_K27vs2KPEe6SUplaisCSHQ" target="_K27vsGKPEe6SUplaisCSHQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vw2KPEe6SUplaisCSHQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K27vxGKPEe6SUplaisCSHQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K27vxWKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K27vxmKPEe6SUplaisCSHQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2yvOIGKeEe6Gj5K04qXrvQ" type="4001" element="_2ytY8GKeEe6Gj5K04qXrvQ" source="_K27vsGKPEe6SUplaisCSHQ" target="_xlUHAGKeEe6Gj5K04qXrvQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2yv1MGKeEe6Gj5K04qXrvQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2yv1MWKeEe6Gj5K04qXrvQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2yvOIWKeEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2yvOImKeEe6Gj5K04qXrvQ" points="[0, 9, -29, -248]$[6, 219, -23, -38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2yxqYGKeEe6Gj5K04qXrvQ" id="(0.48333333333333334,0.85)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XLUEsGKvEe6Jdd_cFX0v8A" type="4001" element="_XLQaUGKvEe6Jdd_cFX0v8A" source="_ngdIAGQsEe6h_5UvdM1dDg" target="_P3R2YGKvEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XLUrwGKvEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XLUrwWKvEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XLUEsWKvEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XLUEsmKvEe6Jdd_cFX0v8A" points="[3, 13, -169, -128]$[3, 109, -169, -32]$[118, 109, -54, -32]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZZDuoGKvEe6Jdd_cFX0v8A" id="(0.39166666666666666,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jLbAkmKvEe6Jdd_cFX0v8A" type="4001" element="_jLaZgGKvEe6Jdd_cFX0v8A" source="_P3R2YGKvEe6Jdd_cFX0v8A" target="_fD7mw2KvEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jLbnoGKvEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jLbnoWKvEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jLbAk2KvEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jLbAlGKvEe6Jdd_cFX0v8A" points="[1, -34, 1, 57]$[1, -106, 1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_M6fNwGKyEe6Jdd_cFX0v8A" id="(0.9855072463768116,0.5217391304347826)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TYdzQGKxEe6Jdd_cFX0v8A" type="4001" element="_TYdMMGKxEe6Jdd_cFX0v8A" source="_xlUHAGKeEe6Gj5K04qXrvQ" target="_5cGX4GKwEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYdzQ2KxEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TYdzRGKxEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYdzQWKxEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TYdzQmKxEe6Jdd_cFX0v8A" points="[32, -7, -68, -4]$[98, -22, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TYfBYGKxEe6Jdd_cFX0v8A" id="(0.7935483870967742,0.5324675324675324)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GtgHEmKyEe6Jdd_cFX0v8A" type="4001" element="_GtfgAGKyEe6Jdd_cFX0v8A" source="_5cGX4GKwEe6Jdd_cFX0v8A" target="_K27vsGKPEe6SUplaisCSHQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GtgHFWKyEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GtgHFmKyEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GtgHE2KyEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GtgHFGKyEe6Jdd_cFX0v8A" points="[0, -21, 108, 179]$[0, -184, 108, 16]$[-85, -184, 23, 16]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GthVMGKyEe6Jdd_cFX0v8A" id="(0.8083333333333333,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kO0lAGK0Ee6hcJAWPaGpNw" type="4001" element="_kOzW4GK0Ee6hcJAWPaGpNw" source="_delAQGK0Ee6hcJAWPaGpNw" target="_rFvdZGaBEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kO0lA2K0Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kO0lBGK0Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kO0lAWK0Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kO0lAmK0Ee6hcJAWPaGpNw" points="[30, -4, -69, -2]$[91, -15, -8, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kO1zIGK0Ee6hcJAWPaGpNw" id="(0.7972972972972973,0.5135135135135135)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FssqAGK1Ee6hcJAWPaGpNw" type="4001" element="_FskuMGK1Ee6hcJAWPaGpNw" source="_rFvdZGaBEe6nVstEweJU5Q" target="_A0fk8GK1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FssqA2K1Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FssqBGK1Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FssqAWK1Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FssqAmK1Ee6hcJAWPaGpNw" points="[-1, 20, 0, -67]$[-2, 82, -1, -5]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FstREGK1Ee6hcJAWPaGpNw" id="(0.4863013698630137,0.0684931506849315)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JKdKUGK1Ee6hcJAWPaGpNw" type="4001" element="_JKcjQGK1Ee6hcJAWPaGpNw" source="_A0fk8GK1Ee6hcJAWPaGpNw" target="_HNXLg2K1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JKdKU2K1Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JKdKVGK1Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JKdKUWK1Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JKdKUmK1Ee6hcJAWPaGpNw" points="[9, -4, -74, -3]$[76, -15, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JKeYcGK1Ee6hcJAWPaGpNw" id="(0.9383561643835616,0.5068493150684932)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q4qCoGQbEe6w1fQx6ik-6g" type="4001" element="_q4jU8GQbEe6w1fQx6ik-6g" source="_rFvdZGaBEe6nVstEweJU5Q" target="_o9TJMGQbEe6w1fQx6ik-6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q4qCo2QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q4qCpGQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q4qCoWQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q4qComQbEe6w1fQx6ik-6g" points="[14, -7, -135, -8]$[99, -7, -50, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rjLmUmQbEe6w1fQx6ik-6g" type="4001" element="_rjK_QGQbEe6w1fQx6ik-6g" source="_o9TJMGQbEe6w1fQx6ik-6g" target="_p0748GK0Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rjMNYGQbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rjMNYWQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rjLmU2QbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rjLmVGQbEe6w1fQx6ik-6g" points="[13, -3, -83, 0]$[81, -3, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rjM0cGQbEe6w1fQx6ik-6g" id="(0.87,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xIHOgGQbEe6w1fQx6ik-6g" type="4001" element="_xH9dgGQbEe6w1fQx6ik-6g" source="_HNXLg2K1Ee6hcJAWPaGpNw" target="_sgne8GQbEe6w1fQx6ik-6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xIHOg2QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xIHOhGQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xIHOgWQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xIHOgmQbEe6w1fQx6ik-6g" points="[20, 2, -55, 0]$[50, 2, -25, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xIIcoGQbEe6w1fQx6ik-6g" id="(0.17857142857142858,0.5142857142857142)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xuTr0GQbEe6w1fQx6ik-6g" type="4001" element="_xuTEwGQbEe6w1fQx6ik-6g" source="_sgne8GQbEe6w1fQx6ik-6g" target="_No99AGK1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xuTr02QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xuTr1GQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xuTr0WQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xuTr0mQbEe6w1fQx6ik-6g" points="[9, 4, -40, 4]$[53, 14, 4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xuUS4GQbEe6w1fQx6ik-6g" id="(0.9357142857142857,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GeHLoGQwEe6h_5UvdM1dDg" type="4001" element="_GeCTIGQwEe6h_5UvdM1dDg" source="_5cGX4GKwEe6Jdd_cFX0v8A" target="_UAp5gGZzEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GeHLo2QwEe6h_5UvdM1dDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GeHLpGQwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GeHLoWQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GeHLomQwEe6h_5UvdM1dDg" points="[21, 1, -90, 0]$[105, 1, -6, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GeIZwGQwEe6h_5UvdM1dDg" id="(0.2,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sj8VA2QwEe6h_5UvdM1dDg" type="4001" element="_Sj8VAGQwEe6h_5UvdM1dDg" source="_SmLfkGZzEe6nVstEweJU5Q" target="_delAQGK0Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sj8VBmQwEe6h_5UvdM1dDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sj8VB2QwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sj8VBGQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sj8VBWQwEe6h_5UvdM1dDg" points="[14, -2, -101, 13]$[101, -17, -14, -2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Sj9jIGQwEe6h_5UvdM1dDg" id="(0.0945945945945946,0.40540540540540543)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bsFlQWQwEe6h_5UvdM1dDg" type="4002" element="_bsFlQGQwEe6h_5UvdM1dDg" source="_UAp5gGZzEe6nVstEweJU5Q" target="_SmLfkGZzEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bsGMUGQwEe6h_5UvdM1dDg" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bsGMUWQwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bsFlQmQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bsFlQ2QwEe6h_5UvdM1dDg" points="[14, -1, 494, -407]$[153, -1, 633, -407]$[153, 271, 633, -135]$[-480, 271, 0, -135]$[-480, 391, 0, -15]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MIvHwGaDEe6nVstEweJU5Q" type="4001" element="_MIugsGaDEe6nVstEweJU5Q" source="_6YO6l2aCEe6nVstEweJU5Q" target="_B2Vq4GaDEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MIvHw2aDEe6nVstEweJU5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MIvHxGaDEe6nVstEweJU5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MIvHwWaDEe6nVstEweJU5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MIvHwmaDEe6nVstEweJU5Q" points="[12, 13, -44, -113]$[12, 122, -44, -4]$[36, 122, -20, -4]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MIvu0GaDEe6nVstEweJU5Q" id="(0.2,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7gVVoGaDEe6nVstEweJU5Q" type="4001" element="_7gTgcGaDEe6nVstEweJU5Q" source="_HNXLg2K1Ee6hcJAWPaGpNw" target="_y6_3gGaDEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7gVVo2aDEe6nVstEweJU5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7gVVpGaDEe6nVstEweJU5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7gVVoWaDEe6nVstEweJU5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7gVVomaDEe6nVstEweJU5Q" points="[-1, 20, -104, -109]$[-1, 128, -104, -1]$[88, 128, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dhKWsWaEEe6nVstEweJU5Q" type="4001" element="_dhJvoGaEEe6nVstEweJU5Q" source="_1R7So2aDEe6nVstEweJU5Q" target="_6YO6kGaCEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dhK9wGaEEe6nVstEweJU5Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dhK9wWaEEe6nVstEweJU5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dhKWsmaEEe6nVstEweJU5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dhKWs2aEEe6nVstEweJU5Q" points="[14, -3, -113, -2]$[61, -3, -66, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6tNaIGaEEe6nVstEweJU5Q" type="4002" element="_6tMzEGaEEe6nVstEweJU5Q" source="_y6_3gGaDEe6nVstEweJU5Q" target="_1R7So2aDEe6nVstEweJU5Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6tNaI2aEEe6nVstEweJU5Q" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6tNaJGaEEe6nVstEweJU5Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6tNaIWaEEe6nVstEweJU5Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6tNaImaEEe6nVstEweJU5Q" points="[15, 0, 81, 1143]$[208, 0, 274, 1143]$[208, -711, 274, 432]$[-152, -711, -86, 432]$[-152, -1143, -86, 0]$[-81, -1143, -15, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
