<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_K27IcGKPEe6SUplaisCSHQ" name="MonDiagramme" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_K27IcWKPEe6SUplaisCSHQ" name="Département MSSC">
      <elements xmi:type="process:Lane" xmi:id="_K27IcmKPEe6SUplaisCSHQ" name="Etudiant" actor="_-voTkGKbEe6Gj5K04qXrvQ">
        <elements xmi:type="process:StartEvent" xmi:id="_K27Ic2KPEe6SUplaisCSHQ" name="Démarrer1" outgoing="_K27vjGKPEe6SUplaisCSHQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K27IdGKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K27IdWKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K27IdmKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_K27Id2KPEe6SUplaisCSHQ" name="Remplir le formulaire" outgoing="_2ytY8GKeEe6Gj5K04qXrvQ" incoming="_K27vjGKPEe6SUplaisCSHQ _GtfgAGKyEe6Jdd_cFX0v8A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_K27IeGKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_K27IeWKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_K27IemKPEe6SUplaisCSHQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_qG01wGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01wWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01wmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01w2QeEe6w1fQx6ik-6g" name="formulaireInput.prenom" content="formulaireInput?.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01xGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01xWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01xmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01x2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01yGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01yWQeEe6w1fQx6ik-6g" name="formulaireInput.nom" content="formulaireInput?.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01ymQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01y2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01zGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01zWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01zmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01z2QeEe6w1fQx6ik-6g" name="formulaireInput.motifSejour" content="formulaireInput?.motifSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG010GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG010WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMotifSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG010mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0102QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG011GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG011WQeEe6w1fQx6ik-6g" name="formulaireInput.moisRetour" content="formulaireInput?.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG011mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG0112QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG012GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG012WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG012mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0122QeEe6w1fQx6ik-6g" name="formulaireInput.moisDepart" content="formulaireInput?.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG013GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG013WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG015GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG015WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG015mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0152QeEe6w1fQx6ik-6g" name="formulaireInput.mail" content="formulaireInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG016GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG016WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG016mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0162QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG017GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG017WQeEe6w1fQx6ik-6g" name="formulaireInput.specialite" content="formulaireInput?.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG017mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG0172QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG018GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG018WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG018mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG0182QeEe6w1fQx6ik-6g" name="formulaireInput.duree" content="formulaireInput?.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG019GQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG019WQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG019mQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG0192QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01-GQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01-WQeEe6w1fQx6ik-6g" name="formulaireInput.secteurGeographique" content="formulaireInput?.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG01-mQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG01-2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG01_GQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG01_WQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG01_mQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG01_2QeEe6w1fQx6ik-6g" name="formulaireInput.paysSejour" content="formulaireInput?.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02AGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02AWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02AmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02A2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02BGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02BWQeEe6w1fQx6ik-6g" name="formulaireInput.villeSejour" content="formulaireInput?.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02BmQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02B2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02CGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02CWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02CmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02C2QeEe6w1fQx6ik-6g" name="formulaireInput.universiteSejour" content="formulaireInput?.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02DGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02DWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02DmQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02D2QeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02EGQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02EWQeEe6w1fQx6ik-6g" name="formulaireInput.departementSejour" content="formulaireInput?.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02EmQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02E2QeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qG02FGQeEe6w1fQx6ik-6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qG02FWQeEe6w1fQx6ik-6g" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qG02FmQeEe6w1fQx6ik-6g" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qG02F2QeEe6w1fQx6ik-6g" name="formulaireInput.specialiteSejour" content="formulaireInput?.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qG02GGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qG02GWQeEe6w1fQx6ik-6g" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_K27Ie2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_K27vgGKPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_K27vgWKPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_K27vgmKPEe6SUplaisCSHQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_K27vg2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_K27vhGKPEe6SUplaisCSHQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_f8EoAGQVEe6LY9FT6NOGNw" name="FormulaireEleve" content="66fd8d94-65b6-46e6-9117-d4712bd07c00" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_K27vhmKPEe6SUplaisCSHQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_qG01sGQeEe6w1fQx6ik-6g" name="formulaireInput" type="COMPLEX" dataReference="formulaire" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01sWQeEe6w1fQx6ik-6g" name="prenom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01smQeEe6w1fQx6ik-6g" name="nom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01s2QeEe6w1fQx6ik-6g" name="motifSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01tGQeEe6w1fQx6ik-6g" name="moisRetour" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01tWQeEe6w1fQx6ik-6g" name="moisDepart" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01t2QeEe6w1fQx6ik-6g" name="mail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01uGQeEe6w1fQx6ik-6g" name="specialite" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01uWQeEe6w1fQx6ik-6g" name="duree" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01umQeEe6w1fQx6ik-6g" name="secteurGeographique" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01u2QeEe6w1fQx6ik-6g" name="paysSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vGQeEe6w1fQx6ik-6g" name="villeSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vWQeEe6w1fQx6ik-6g" name="universiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01vmQeEe6w1fQx6ik-6g" name="departementSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_qG01v2QeEe6w1fQx6ik-6g" name="specialiteSejour" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_K27vh2KPEe6SUplaisCSHQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_6_CMQGKaEe6Gj5K04qXrvQ" name="Secrétariat" actor="_VmvOMGKcEe6Gj5K04qXrvQ">
        <elements xmi:type="process:Task" xmi:id="_xlSR0GKeEe6Gj5K04qXrvQ" name="Contrôle des informations" outgoing="_TYdMMGKxEe6Jdd_cFX0v8A" incoming="_2ytY8GKeEe6Gj5K04qXrvQ" actor="_-voTkGKbEe6Gj5K04qXrvQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xlS44WKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xlS44GKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xlS44mKeEe6Gj5K04qXrvQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_q-0YMmQfEe6LY9FT6NOGNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_q-0YM2QfEe6LY9FT6NOGNw" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_q-0YNGQfEe6LY9FT6NOGNw" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_q-0YNWQfEe6LY9FT6NOGNw" name="formulaireInput.accept" content="formulaireInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_q-0YNmQfEe6LY9FT6NOGNw" name="formulaireInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_q-0YN2QfEe6LY9FT6NOGNw" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xlS442KeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xlS45GKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xlS45WKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xlS452KeEe6Gj5K04qXrvQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xlS45mKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_ngcg8GQsEe6h_5UvdM1dDg" name="1min" outgoing="_XLQaUGKvEe6Jdd_cFX0v8A">
            <condition xmi:type="expression:Expression" xmi:id="__oCa4GKeEe6Gj5K04qXrvQ" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xlS46WKeEe6Gj5K04qXrvQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_zxnDgGQfEe6LY9FT6NOGNw" name="FormulaireControle" content="df9b8c2f-e776-4c93-9238-81b8c7d1af40" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xlS46GKeEe6Gj5K04qXrvQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_q-0YMGQfEe6LY9FT6NOGNw" name="formulaireInput" type="COMPLEX" dataReference="formulaire" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_q-0YMWQfEe6LY9FT6NOGNw" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xlS462KeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_5cFJwGKwEe6Jdd_cFX0v8A" name="Porte1" outgoing="_GtfgAGKyEe6Jdd_cFX0v8A _GeCTIGQwEe6h_5UvdM1dDg" incoming="_TYdMMGKxEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5cFw0WKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5cFw0GKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5cFw0mKwEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_P3AwoGKvEe6Jdd_cFX0v8A" name="Traitement avec du retard" outgoing="_jLaZgGKvEe6Jdd_cFX0v8A" incoming="_XLQaUGKvEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_P3HeUWKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_P3HeUGKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_P3HeUmKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_klY9sGQvEe6h_5UvdM1dDg" name="Traitement avec du retard" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_klY9sWQvEe6h_5UvdM1dDg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9smQvEe6h_5UvdM1dDg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_klY9s2QvEe6h_5UvdM1dDg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9tGQvEe6h_5UvdM1dDg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_klY9tWQvEe6h_5UvdM1dDg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9tmQvEe6h_5UvdM1dDg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_klY9t2QvEe6h_5UvdM1dDg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9uGQvEe6h_5UvdM1dDg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_klY9uWQvEe6h_5UvdM1dDg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9umQvEe6h_5UvdM1dDg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_klY9u2QvEe6h_5UvdM1dDg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9vGQvEe6h_5UvdM1dDg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_klY9vWQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9vmQvEe6h_5UvdM1dDg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_klY9v2QvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9wGQvEe6h_5UvdM1dDg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_klY9wWQvEe6h_5UvdM1dDg" name="alexander.duchemin@entreprise.com" content="alexander.duchemin@entreprise.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9wmQvEe6h_5UvdM1dDg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_klY9w2QvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9xGQvEe6h_5UvdM1dDg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_klY9xWQvEe6h_5UvdM1dDg" name="to()" content="formulaire.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.FormObject" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY9xmQvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9x2QvEe6h_5UvdM1dDg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_klY9yGQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9yWQvEe6h_5UvdM1dDg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_klY9ymQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9y2QvEe6h_5UvdM1dDg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_klY9zGQvEe6h_5UvdM1dDg" name="Dossier en cours de traitement" content="Dossier en cours de traitement" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9zWQvEe6h_5UvdM1dDg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_klY9zmQvEe6h_5UvdM1dDg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY9z2QvEe6h_5UvdM1dDg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_klY90GQvEe6h_5UvdM1dDg" name="&lt;pattern-expression>" content="&lt;p>&lt;span style=&quot;font-size:12px&quot;>Bonjour ${formulaire.prenom} ${formulaire.nom}&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:12px&quot;>&lt;span style=&quot;font-family:Calibri&quot;>&lt;span style=&quot;font-family:Calibri&quot;>Votre dossier est bien en cours de traitement mais avec du retard.&lt;/span>&lt;/span>&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:12px&quot;>Le secr&amp;eacute;tariat&lt;/span>&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_klY90WQvEe6h_5UvdM1dDg" name="formulaire.prenom" content="formulaire.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_klY90mQvEe6h_5UvdM1dDg" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY902QvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_klY91GQvEe6h_5UvdM1dDg" name="formulaire.nom" content="formulaire.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_klY91WQvEe6h_5UvdM1dDg" name="formulaire" content="formulaire" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_klY91mQvEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY912QvEe6h_5UvdM1dDg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_klY92GQvEe6h_5UvdM1dDg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY92WQvEe6h_5UvdM1dDg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_klY92mQvEe6h_5UvdM1dDg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY922QvEe6h_5UvdM1dDg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_klY93GQvEe6h_5UvdM1dDg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_klY93WQvEe6h_5UvdM1dDg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_klY93mQvEe6h_5UvdM1dDg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_P3HeU2KvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_P3HeVGKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_P3HeVWKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_P3IFYWKvEe6Jdd_cFX0v8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_P3IFYGKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fD6_sGKvEe6Jdd_cFX0v8A" name="Fin1" incoming="_jLaZgGKvEe6Jdd_cFX0v8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fD7mwWKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fD7mwGKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fD7mwmKvEe6Jdd_cFX0v8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_PJF-wGQwEe6h_5UvdM1dDg" name="Fin5" incoming="_GeCTIGQwEe6h_5UvdM1dDg" outgoingMessages="_bsFlQGQwEe6h_5UvdM1dDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DtooEmQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DtooEWQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DtooE2QwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_bsBT0GQwEe6h_5UvdM1dDg" name="mess">
            <correlation xmi:type="process:Correlation" xmi:id="_bsBT0WQwEe6h_5UvdM1dDg">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_bsBT0mQwEe6h_5UvdM1dDg"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_bsBT02QwEe6h_5UvdM1dDg" name="Relation internationale" content="Relation internationale" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_bsBT1GQwEe6h_5UvdM1dDg" name="Démarrer2" content="Démarrer2" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_bsBT1WQwEe6h_5UvdM1dDg">
              <expressions xmi:type="expression:ListExpression" xmi:id="_bsBT1mQwEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_bsBT12QwEe6h_5UvdM1dDg" name="messPrenom" content="messPrenom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_bsBT2GQwEe6h_5UvdM1dDg" name="newScript()" content="formulaire.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bsBT2WQwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_iy7sIGQwEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_iy7sIWQwEe6h_5UvdM1dDg" name="messNom" content="messNom" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_iy7sImQwEe6h_5UvdM1dDg" name="newScript()" content="formulaire.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iy7sI2QwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_8DxeQGQwEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_8DxeQWQwEe6h_5UvdM1dDg" name="messNationnalite" content="messNationnalite" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_8DxeQmQwEe6h_5UvdM1dDg" name="newScript()" content="formulaire.nationnalite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8DxeQ2QwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_QyYbUGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_QyYbUWQxEe6h_5UvdM1dDg" name="messMotifSejour" content="messMotifSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_QyYbUmQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.motifSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QyYbU2QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_QyYbVGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_QyYbVWQxEe6h_5UvdM1dDg" name="messMoisRetour" content="messMoisRetour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_QyYbVmQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_VPA-sGQxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_ZO-0MGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_ZO-0MWQxEe6h_5UvdM1dDg" name="messMoisDepart" content="messMoisDepart" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_ZO-0MmQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ZO-0M2QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_cyld0GQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_cyld0WQxEe6h_5UvdM1dDg" name="messCommentaires" content="messCommentaires" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_cyld0mQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.commentaires" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cyld02QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_h_5QMGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_h_5QMWQxEe6h_5UvdM1dDg" name="messMail" content="messMail" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_h_5QMmQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_h_5QM2QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_m0MFoGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_m0MFoWQxEe6h_5UvdM1dDg" name="messSpecialite" content="messSpecialite" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_m0MFomQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_m0MFo2QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_q3bRkGQxEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_q3bRkWQxEe6h_5UvdM1dDg" name="messDuree" content="messDuree" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_q3bRkmQxEe6h_5UvdM1dDg" name="newScript()" content="formulaire.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_q3bRk2QxEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCQGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCQWQyEe6h_5UvdM1dDg" name="messSecteurGeographique" content="messSecteurGeographique" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCQmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCQ2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCRGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCRWQyEe6h_5UvdM1dDg" name="messPaysSejour" content="messPaysSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCRmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCR2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCSGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCSWQyEe6h_5UvdM1dDg" name="messVilleSejour" content="messVilleSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCSmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCS2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCTGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCTWQyEe6h_5UvdM1dDg" name="messUniversiteSejour" content="messUniversiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCTmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCT2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCUGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCUWQyEe6h_5UvdM1dDg" name="messDepartementSejour" content="messDepartementSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCUmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCU2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_KHgCVGQyEe6h_5UvdM1dDg">
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCVWQyEe6h_5UvdM1dDg" name="messSpecialiteSejour" content="messSpecialiteSejour" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_KHgCVmQyEe6h_5UvdM1dDg" name="newScript()" content="formulaire.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KHgCV2QyEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_QZNXEGQVEe6LY9FT6NOGNw" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject">
        <defaultValue xmi:type="expression:Expression" xmi:id="_QZNXEWQVEe6LY9FT6NOGNw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_K27viGKPEe6SUplaisCSHQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_brrOMGQzEe6h_5UvdM1dDg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_K27vimKPEe6SUplaisCSHQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_K27vi2KPEe6SUplaisCSHQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K27vjGKPEe6SUplaisCSHQ" target="_K27Id2KPEe6SUplaisCSHQ" source="_K27Ic2KPEe6SUplaisCSHQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K27vjWKPEe6SUplaisCSHQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_K27vjmKPEe6SUplaisCSHQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2ytY8GKeEe6Gj5K04qXrvQ" target="_xlSR0GKeEe6Gj5K04qXrvQ" source="_K27Id2KPEe6SUplaisCSHQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2yuAAGKeEe6Gj5K04qXrvQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2yuAAWKeEe6Gj5K04qXrvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XLQaUGKvEe6Jdd_cFX0v8A" target="_P3AwoGKvEe6Jdd_cFX0v8A" source="_ngcg8GQsEe6h_5UvdM1dDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XLRBYGKvEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_XLRBYWKvEe6Jdd_cFX0v8A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jLaZgGKvEe6Jdd_cFX0v8A" target="_fD6_sGKvEe6Jdd_cFX0v8A" source="_P3AwoGKvEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jLbAkGKvEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_jLbAkWKvEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TYdMMGKxEe6Jdd_cFX0v8A" target="_5cFJwGKwEe6Jdd_cFX0v8A" source="_xlSR0GKeEe6Gj5K04qXrvQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TYdMMWKxEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_TYdMMmKxEe6Jdd_cFX0v8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GtfgAGKyEe6Jdd_cFX0v8A" target="_K27Id2KPEe6SUplaisCSHQ" source="_5cFJwGKwEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GtgHEGKyEe6Jdd_cFX0v8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_GtgHEWKyEe6Jdd_cFX0v8A" name="!isAccept" content="formulaire.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_H5p8kGQwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GeCTIGQwEe6h_5UvdM1dDg" target="_PJF-wGQwEe6h_5UvdM1dDg" source="_5cFJwGKwEe6Jdd_cFX0v8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GeC6MGQwEe6h_5UvdM1dDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_GeC6MWQwEe6h_5UvdM1dDg" name="!isAccept" content="formulaire.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JycDIGQwEe6h_5UvdM1dDg" name="formulaire" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_-voTkGKbEe6Gj5K04qXrvQ" name="Etudiant" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_VmvOMGKcEe6Gj5K04qXrvQ" name="Secrétaire"/>
      <contract xmi:type="process:Contract" xmi:id="_K27vkGKPEe6SUplaisCSHQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vkWKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vkmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vk2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vlGKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vlWKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vlmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vl2KPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vmGKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vmWKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vmmKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vm2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vnGKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_K27vnWKPEe6SUplaisCSHQ">
        <name xmi:type="expression:Expression" xmi:id="_K27vnmKPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_K27vn2KPEe6SUplaisCSHQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_7c8QQGKaEe6Gj5K04qXrvQ" name="Relation internationale">
      <elements xmi:type="process:Lane" xmi:id="_8ExFQGKaEe6Gj5K04qXrvQ" name="Management" actor="_oAWCwGKcEe6Gj5K04qXrvQ">
        <elements xmi:type="process:Task" xmi:id="_deYzAGK0Ee6hcJAWPaGpNw" name="Contrôle les informations" outgoing="_kOzW4GK0Ee6hcJAWPaGpNw" incoming="_Sj8VAGQwEe6h_5UvdM1dDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_deb2UWK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_deb2UGK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_deb2UmK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HO2QyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HPGQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HPWQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HPmQyEe6h_5UvdM1dDg" name="formulaireRIInput.moisRetour" content="formulaireRIInput?.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HP2QyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HQGQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HQWQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HQmQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HQ2QyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HRGQyEe6h_5UvdM1dDg" name="formulaireRIInput.moisDepart" content="formulaireRIInput?.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HRWQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HRmQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HR2QyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HSGQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HSWQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HSmQyEe6h_5UvdM1dDg" name="formulaireRIInput.duree" content="formulaireRIInput?.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HS2QyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HTGQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HTWQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HTmQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HT2QyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HUGQyEe6h_5UvdM1dDg" name="formulaireRIInput.secteurGeographique" content="formulaireRIInput?.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HUWQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HUmQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HU2QyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HVGQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HVWQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HVmQyEe6h_5UvdM1dDg" name="formulaireRIInput.paysSejour" content="formulaireRIInput?.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HV2QyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HWGQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HWWQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HWmQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HW2QyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HXGQyEe6h_5UvdM1dDg" name="formulaireRIInput.villeSejour" content="formulaireRIInput?.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HXWQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HXmQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HX2QyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HYGQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HYWQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HYmQyEe6h_5UvdM1dDg" name="formulaireRIInput.universiteSejour" content="formulaireRIInput?.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HY2QyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HZGQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HZWQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HZmQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HZ2QyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HaGQyEe6h_5UvdM1dDg" name="formulaireRIInput.departementSejour" content="formulaireRIInput?.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HaWQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HamQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3Ha2QyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HbGQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3HbWQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HbmQyEe6h_5UvdM1dDg" name="formulaireRIInput.specialiteSejour" content="formulaireRIInput?.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3Hb2QyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HcGQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pC3HcWQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pC3HcmQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pC3Hc2QyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pC3HdGQyEe6h_5UvdM1dDg" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pC3HdWQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pC3HdmQyEe6h_5UvdM1dDg" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_deb2U2K0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_deb2VGK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_deb2VWK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_deb2V2K0Ee6hcJAWPaGpNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_deb2VmK0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_deb2WWK0Ee6hcJAWPaGpNw">
            <targetForm xmi:type="expression:Expression" xmi:id="__Bl6QGQwEe6h_5UvdM1dDg" name="verificationSejour" content="178f7025-628a-4e28-9d16-ceba1bece9e4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_deb2WGK0Ee6hcJAWPaGpNw">
            <inputs xmi:type="process:ContractInput" xmi:id="_pC3HMGQyEe6h_5UvdM1dDg" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HMWQyEe6h_5UvdM1dDg" name="moisRetour" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HMmQyEe6h_5UvdM1dDg" name="moisDepart" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HM2QyEe6h_5UvdM1dDg" name="duree" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HNGQyEe6h_5UvdM1dDg" name="secteurGeographique" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HNWQyEe6h_5UvdM1dDg" name="paysSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HNmQyEe6h_5UvdM1dDg" name="villeSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HN2QyEe6h_5UvdM1dDg" name="universiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HOGQyEe6h_5UvdM1dDg" name="departementSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HOWQyEe6h_5UvdM1dDg" name="specialiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pC3HOmQyEe6h_5UvdM1dDg" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_deb2W2K0Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_jM4m4GK0Ee6hcJAWPaGpNw" name="Porte2" outgoing="_FskuMGK1Ee6hcJAWPaGpNw _q4jU8GQbEe6w1fQx6ik-6g" incoming="_kOzW4GK0Ee6hcJAWPaGpNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jM5N8WK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jM5N8GK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jM5N8mK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_p06q0GK0Ee6hcJAWPaGpNw" name="Fin3" incoming="_rjK_QGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_p07R4WK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_p07R4GK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_p07R4mK0Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_A0eW0GK1Ee6hcJAWPaGpNw" name="Vérifier dossier scolaire" outgoing="_JKcjQGK1Ee6hcJAWPaGpNw" incoming="_FskuMGK1Ee6hcJAWPaGpNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A0e94WK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A0e94GK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A0e94mK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_dnmfoGREEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dnmfoWREEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dnmfomREEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dnmfo2REEe6Z4r-KrE3rtQ" name="formulaireRIInput.prenom" content="formulaireRIInput?.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnmfpGREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dnmfpWREEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dnmfpmREEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dnmfp2REEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dnmfqGREEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dnmfqWREEe6Z4r-KrE3rtQ" name="formulaireRIInput.nom" content="formulaireRIInput?.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnmfqmREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dnmfq2REEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dnmfrGREEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dnmfrWREEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dnmfrmREEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dnmfr2REEe6Z4r-KrE3rtQ" name="formulaireRIInput.mail" content="formulaireRIInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnmfsGREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dnmfsWREEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dnmfsmREEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dnmfs2REEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dnmftGREEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dnmftWREEe6Z4r-KrE3rtQ" name="formulaireRIInput.specialite" content="formulaireRIInput?.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnmftmREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dnmft2REEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_dnmfuGREEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dnmfuWREEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dnmfumREEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dnmfu2REEe6Z4r-KrE3rtQ" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnmfvGREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dnmfvWREEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A0e942K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A0e95GK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A0e95WK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A0e952K1Ee6hcJAWPaGpNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A0e95mK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_A0e96WK1Ee6hcJAWPaGpNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_bvJY8GQzEe6h_5UvdM1dDg" name="verificationDossier" content="af0ea0be-e3b9-4ed3-81f4-d59b94d5daed" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_A0e96GK1Ee6hcJAWPaGpNw">
            <inputs xmi:type="process:ContractInput" xmi:id="_dnl4kGREEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_dnl4kWREEe6Z4r-KrE3rtQ" name="prenom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_dnl4kmREEe6Z4r-KrE3rtQ" name="nom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_dnl4k2REEe6Z4r-KrE3rtQ" name="mail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_dnl4lGREEe6Z4r-KrE3rtQ" name="specialite" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_dnl4lWREEe6Z4r-KrE3rtQ" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_A0e962K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_HNWkcGK1Ee6hcJAWPaGpNw" name="Porte3" outgoing="_CvtfAGK2Ee6hcJAWPaGpNw _xH9dgGQbEe6w1fQx6ik-6g" incoming="_JKcjQGK1Ee6hcJAWPaGpNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HNXLgWK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HNXLgGK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HNXLgmK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_No9V8GK1Ee6hcJAWPaGpNw" name="Fin4" incoming="_xuTEwGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_No9V8mK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_No9V8WK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_No9V82K1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5yMKYGK1Ee6hcJAWPaGpNw" name="Formulaire engagement" outgoing="_hMm6wGLAEe6hcJAWPaGpNw" incoming="_CvtfAGK2Ee6hcJAWPaGpNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5yMxcWK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5yMxcGK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5yMxcmK1Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_FryKT2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKUGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKUWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKUmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.prenom" content="formulaireRIInput?.prenom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKU2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKVGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setPrenom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKVWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKVmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKV2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKWGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.nom" content="formulaireRIInput?.nom" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKWWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKWmRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setNom">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKW2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKXGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKXWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKXmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.moisRetour" content="formulaireRIInput?.moisRetour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKX2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKYGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setMoisRetour">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKYWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKYmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKY2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKZGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.moisDepart" content="formulaireRIInput?.moisDepart" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKZWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKZmRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setMoisDepart">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKZ2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKaGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKaWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKamRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.mail" content="formulaireRIInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKa2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKbGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKbWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKbmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKb2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKcGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.specialite" content="formulaireRIInput?.specialite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKcWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKcmRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setSpecialite">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKc2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKdGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKdWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKdmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.duree" content="formulaireRIInput?.duree" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKd2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKeGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setDuree">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKeWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKemRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKe2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKfGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.secteurGeographique" content="formulaireRIInput?.secteurGeographique" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKfWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKfmRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setSecteurGeographique">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKf2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKgGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKgWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKgmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.paysSejour" content="formulaireRIInput?.paysSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKg2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKhGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setPaysSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKhWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKhmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKh2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKiGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.villeSejour" content="formulaireRIInput?.villeSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKiWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKimRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setVilleSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKi2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKjGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKjWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKjmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.universiteSejour" content="formulaireRIInput?.universiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKj2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKkGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setUniversiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKkWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKkmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKk2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKlGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.departementSejour" content="formulaireRIInput?.departementSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKlWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKlmRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setDepartementSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKl2RFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKmGRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKmWRFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKmmRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.specialiteSejour" content="formulaireRIInput?.specialiteSejour" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKm2RFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKnGRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setSpecialiteSejour">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FryKnWRFEe6Z4r-KrE3rtQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FryKnmRFEe6Z4r-KrE3rtQ" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FryKn2RFEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FryKoGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput.accept" content="formulaireRIInput?.accept" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FryKoWRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FryKomRFEe6Z4r-KrE3rtQ" type="JAVA_METHOD" expression="setAccept">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5yMxc2K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5yMxdGK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5yMxdWK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5yMxd2K1Ee6hcJAWPaGpNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5yMxdmK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="__3E2QGK7Ee6hcJAWPaGpNw" name="Boundary Minuterie1" outgoing="_1X96IGQbEe6w1fQx6ik-6g">
            <condition xmi:type="expression:Expression" xmi:id="_CTYgoGK8Ee6hcJAWPaGpNw" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5yMxeWK1Ee6hcJAWPaGpNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_HZhecGRFEe6Z4r-KrE3rtQ" name="engagement" content="068a7a97-dcd1-42a1-9ac3-684c24e67397" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5yMxeGK1Ee6hcJAWPaGpNw">
            <inputs xmi:type="process:ContractInput" xmi:id="_FryKQGRFEe6Z4r-KrE3rtQ" name="formulaireRIInput" type="COMPLEX" dataReference="formulaireRI" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKQWRFEe6Z4r-KrE3rtQ" name="prenom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKQmRFEe6Z4r-KrE3rtQ" name="nom" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKQ2RFEe6Z4r-KrE3rtQ" name="moisRetour" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKRGRFEe6Z4r-KrE3rtQ" name="moisDepart" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKRWRFEe6Z4r-KrE3rtQ" name="mail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKRmRFEe6Z4r-KrE3rtQ" name="specialite" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKR2RFEe6Z4r-KrE3rtQ" name="duree" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKSGRFEe6Z4r-KrE3rtQ" name="secteurGeographique" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKSWRFEe6Z4r-KrE3rtQ" name="paysSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKSmRFEe6Z4r-KrE3rtQ" name="villeSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKS2RFEe6Z4r-KrE3rtQ" name="universiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKTGRFEe6Z4r-KrE3rtQ" name="departementSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKTWRFEe6Z4r-KrE3rtQ" name="specialiteSejour" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_FryKTmRFEe6Z4r-KrE3rtQ" name="accept" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5yMxe2K1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_MMcQcGK8Ee6hcJAWPaGpNw" name="Porte4" incoming="_hMm6wGLAEe6hcJAWPaGpNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MMc3gWK8Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MMc3gGK8Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MMc3gmK8Ee6hcJAWPaGpNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_o9SiIGQbEe6w1fQx6ik-6g" name="Rejet formulaire" outgoing="_rjK_QGQbEe6w1fQx6ik-6g" incoming="_q4jU8GQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_o9SiImQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_o9SiIWQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_o9SiI2QbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_o9SiJGQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_o9SiJWQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_o9SiJmQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_o9SiKGQbEe6w1fQx6ik-6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_o9SiJ2QbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_sgmQ0GQbEe6w1fQx6ik-6g" name="Rejet dossier scolaire" outgoing="_xuTEwGQbEe6w1fQx6ik-6g" incoming="_xH9dgGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sgm34WQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sgm34GQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sgm34mQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sgm342QbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sgm35GQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sgm35WQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sgm352QbEe6w1fQx6ik-6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sgm35mQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_z6sD0GQbEe6w1fQx6ik-6g" name="Refus" incoming="_1X96IGQbEe6w1fQx6ik-6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z6sD0mQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z6sD0WQbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z6sD02QbEe6w1fQx6ik-6g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z6sD1GQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z6sD1WQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z6sD1mQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z6sD2GQbEe6w1fQx6ik-6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z6sD12QbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_RzOpwGQwEe6h_5UvdM1dDg" name="Démarrer2" outgoing="_Sj8VAGQwEe6h_5UvdM1dDg" event="mess" incomingMessag="_bsFlQGQwEe6h_5UvdM1dDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RzOpwmQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RzOpwWQwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RzOpw2QwEe6h_5UvdM1dDg" name="" content="" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-AVUGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-AVUWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ttId8GQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-AVUmQyEe6h_5UvdM1dDg" name="messPrenom" content="messPrenom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-AVU2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-A8YGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-A8YWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ugvFIGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-A8YmQyEe6h_5UvdM1dDg" name="messNom" content="messNom" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-A8Y2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-A8ZGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-A8ZWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u1ChMGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-A8ZmQyEe6h_5UvdM1dDg" name="messNationnalite" content="messNationnalite" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-A8Z2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-BjcGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-BjcWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_vPDjsGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-BjcmQyEe6h_5UvdM1dDg" name="messMotifSejour" content="messMotifSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Bjc2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-BjdGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-BjdWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_vkg2UGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-BjdmQyEe6h_5UvdM1dDg" name="messMoisRetour" content="messMoisRetour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Bjd2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-CKgGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-CKgWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_v8c1MGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-CKgmQyEe6h_5UvdM1dDg" name="messMoisDepart" content="messMoisDepart" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-CKg2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-CxkGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-CxkWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wUb3YGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-CxkmQyEe6h_5UvdM1dDg" name="messCommentaires" content="messCommentaires" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Cxk2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-CxlGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-CxlWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wvc_cGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-CxlmQyEe6h_5UvdM1dDg" name="messMail" content="messMail" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Cxl2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-DYoGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-DYoWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xFYzMGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-DYomQyEe6h_5UvdM1dDg" name="messSpecialite" content="messSpecialite" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-DYo2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-DYpGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-DYpWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xfJ-EGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-DYpmQyEe6h_5UvdM1dDg" name="messDuree" content="messDuree" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-DYp2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-D_sGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-D_sWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_x2lmoGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-D_smQyEe6h_5UvdM1dDg" name="messSecteurGeographique" content="messSecteurGeographique" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-D_s2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-EmwGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-EmwWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yax40GQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-EmwmQyEe6h_5UvdM1dDg" name="messPaysSejour" content="messPaysSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Emw2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-EmxGQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-EmxWQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zCagkGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-EmxmQyEe6h_5UvdM1dDg" name="messVilleSejour" content="messVilleSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-Emx2QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-FN0GQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-FN0WQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zWtVkGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-FN0mQyEe6h_5UvdM1dDg" name="messUniversiteSejour" content="messUniversiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-FN02QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-F04GQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-F04WQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_z10TcGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-F04mQyEe6h_5UvdM1dDg" name="messDepartementSejour" content="messDepartementSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-F042QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_M-F05GQyEe6h_5UvdM1dDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_M-F05WQyEe6h_5UvdM1dDg" name="formulaireRI" content="formulaireRI" type="TYPE_VARIABLE" returnType="com.company.model.FormObject">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0QnZEGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_M-F05mQyEe6h_5UvdM1dDg" name="messSpecialiteSejour" content="messSpecialiteSejour" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_M-F052QyEe6h_5UvdM1dDg" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_8XGycGKaEe6Gj5K04qXrvQ" name="Comptabilité" actor="_UZC2kGKdEe6Gj5K04qXrvQ"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_evG_cGQyEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject">
        <defaultValue xmi:type="expression:Expression" xmi:id="_evG_cWQyEe6h_5UvdM1dDg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_7e-3r2KaEe6Gj5K04qXrvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_bvJY8mQzEe6h_5UvdM1dDg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_7e-3sWKaEe6Gj5K04qXrvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_7e-3smKaEe6Gj5K04qXrvQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kOzW4GK0Ee6hcJAWPaGpNw" target="_jM4m4GK0Ee6hcJAWPaGpNw" source="_deYzAGK0Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kOz98GK0Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_kOz98WK0Ee6hcJAWPaGpNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FskuMGK1Ee6hcJAWPaGpNw" target="_A0eW0GK1Ee6hcJAWPaGpNw" source="_jM4m4GK0Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FskuMWK1Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_FskuMmK1Ee6hcJAWPaGpNw" name="isAccept" content="formulaireRI.accept==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YddA4GRCEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JKcjQGK1Ee6hcJAWPaGpNw" target="_HNWkcGK1Ee6hcJAWPaGpNw" source="_A0eW0GK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JKcjQWK1Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_JKcjQmK1Ee6hcJAWPaGpNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CvtfAGK2Ee6hcJAWPaGpNw" target="_5yMKYGK1Ee6hcJAWPaGpNw" source="_HNWkcGK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CvtfAWK2Ee6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_CvtfAmK2Ee6hcJAWPaGpNw" name="isAccept" content="formulaireRI.accept==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_d2AZ8GRCEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hMm6wGLAEe6hcJAWPaGpNw" target="_MMcQcGK8Ee6hcJAWPaGpNw" source="_5yMKYGK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hMnh0GLAEe6hcJAWPaGpNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_hMnh0WLAEe6hcJAWPaGpNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q4jU8GQbEe6w1fQx6ik-6g" target="_o9SiIGQbEe6w1fQx6ik-6g" source="_jM4m4GK0Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q4jU8WQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_q4jU8mQbEe6w1fQx6ik-6g" name="!isAccept" content="formulaireRI.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S-T1cGQzEe6h_5UvdM1dDg" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rjK_QGQbEe6w1fQx6ik-6g" target="_p06q0GK0Ee6hcJAWPaGpNw" source="_o9SiIGQbEe6w1fQx6ik-6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rjLmUGQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_rjLmUWQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xH9dgGQbEe6w1fQx6ik-6g" target="_sgmQ0GQbEe6w1fQx6ik-6g" source="_HNWkcGK1Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xH9dgWQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_xH9dgmQbEe6w1fQx6ik-6g" name="!isAccept" content="formulaireRI.accept==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S1PbMGRCEe6Z4r-KrE3rtQ" name="formulaireRI" dataType="_K27vqGKPEe6SUplaisCSHQ" className="com.company.model.FormObject"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xuTEwGQbEe6w1fQx6ik-6g" target="_No9V8GK1Ee6hcJAWPaGpNw" source="_sgmQ0GQbEe6w1fQx6ik-6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xuTEwWQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_xuTEwmQbEe6w1fQx6ik-6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1X96IGQbEe6w1fQx6ik-6g" target="_z6sD0GQbEe6w1fQx6ik-6g" source="__3E2QGK7Ee6hcJAWPaGpNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1X96IWQbEe6w1fQx6ik-6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1X96ImQbEe6w1fQx6ik-6g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sj8VAGQwEe6h_5UvdM1dDg" target="_deYzAGK0Ee6hcJAWPaGpNw" source="_RzOpwGQwEe6h_5UvdM1dDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sj8VAWQwEe6h_5UvdM1dDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sj8VAmQwEe6h_5UvdM1dDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_oAWCwGKcEe6Gj5K04qXrvQ" name="Directeur" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_UZC2kGKdEe6Gj5K04qXrvQ" name="Comptable"/>
      <contract xmi:type="process:Contract" xmi:id="_7e-3s2KaEe6Gj5K04qXrvQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3oGKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3oWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3omKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3o2KaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3pGKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3pWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3pmKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3p2KaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3qGKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3qWKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3qmKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3q2KaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_7e-3rGKaEe6Gj5K04qXrvQ">
        <name xmi:type="expression:Expression" xmi:id="_7e-3rWKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_7e-3rmKaEe6Gj5K04qXrvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_K27voGKPEe6SUplaisCSHQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_K27voWKPEe6SUplaisCSHQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_K27vomKPEe6SUplaisCSHQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_K27vo2KPEe6SUplaisCSHQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_K27vpGKPEe6SUplaisCSHQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_K27vpWKPEe6SUplaisCSHQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_K27vpmKPEe6SUplaisCSHQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_K27vp2KPEe6SUplaisCSHQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_K27vqGKPEe6SUplaisCSHQ" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_bsFlQGQwEe6h_5UvdM1dDg" name="mess" target="_RzOpwGQwEe6h_5UvdM1dDg" source="_PJF-wGQwEe6h_5UvdM1dDg"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_K27vqWKPEe6SUplaisCSHQ" type="Process" element="_K27IcGKPEe6SUplaisCSHQ" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_K27vqmKPEe6SUplaisCSHQ" type="2007" element="_K27IcWKPEe6SUplaisCSHQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vq2KPEe6SUplaisCSHQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vrGKPEe6SUplaisCSHQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_K27vrWKPEe6SUplaisCSHQ" type="3007" element="_K27IcmKPEe6SUplaisCSHQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_K27vrmKPEe6SUplaisCSHQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_K27vr2KPEe6SUplaisCSHQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_K27vsGKPEe6SUplaisCSHQ" type="3005" element="_K27Id2KPEe6SUplaisCSHQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_K27vsWKPEe6SUplaisCSHQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vsmKPEe6SUplaisCSHQ" x="232" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K27vs2KPEe6SUplaisCSHQ" type="3002" element="_K27Ic2KPEe6SUplaisCSHQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_K27vtGKPEe6SUplaisCSHQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_K27vtWKPEe6SUplaisCSHQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vtmKPEe6SUplaisCSHQ" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_K27vt2KPEe6SUplaisCSHQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_K27vuGKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_K27vuWKPEe6SUplaisCSHQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_K27vumKPEe6SUplaisCSHQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vu2KPEe6SUplaisCSHQ" x="53" y="10" width="1292" height="180"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_6_OZgGKaEe6Gj5K04qXrvQ" type="3007" element="_6_CMQGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_6_PAkGKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6_PAkWKaEe6Gj5K04qXrvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xlUHAGKeEe6Gj5K04qXrvQ" type="3005" element="_xlSR0GKeEe6Gj5K04qXrvQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xlUHAmKeEe6Gj5K04qXrvQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_ngdIAGQsEe6h_5UvdM1dDg" type="3064" element="_ngcg8GQsEe6h_5UvdM1dDg" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_ngdvEGQsEe6h_5UvdM1dDg" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_ngdvEWQsEe6h_5UvdM1dDg" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ngdIAWQsEe6h_5UvdM1dDg"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xlUHAWKeEe6Gj5K04qXrvQ" x="214" y="56" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5cGX4GKwEe6Jdd_cFX0v8A" type="3008" element="_5cFJwGKwEe6Jdd_cFX0v8A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5cGX4mKwEe6Jdd_cFX0v8A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5cGX42KwEe6Jdd_cFX0v8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5cGX4WKwEe6Jdd_cFX0v8A" x="416" y="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P3R2YGKvEe6Jdd_cFX0v8A" type="3027" element="_P3AwoGKvEe6Jdd_cFX0v8A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P3SdcGKvEe6Jdd_cFX0v8A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P3R2YWKvEe6Jdd_cFX0v8A" x="369" y="221" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fD7mw2KvEe6Jdd_cFX0v8A" type="3003" element="_fD6_sGKvEe6Jdd_cFX0v8A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fD7mxWKvEe6Jdd_cFX0v8A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fD7mxmKvEe6Jdd_cFX0v8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fD7mxGKvEe6Jdd_cFX0v8A" x="612" y="241"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PJGl02QwEe6h_5UvdM1dDg" type="3011" element="_PJF-wGQwEe6h_5UvdM1dDg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PJGl1WQwEe6h_5UvdM1dDg" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PJGl1mQwEe6h_5UvdM1dDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PJGl1GQwEe6h_5UvdM1dDg" x="542" y="80" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6_OZgWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6_OZgmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6_OZg2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6_PAkmKaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6_OZhGKaEe6Gj5K04qXrvQ" x="53" y="180" width="1292" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_K27vvGKPEe6SUplaisCSHQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_K27vvWKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_K27vvmKPEe6SUplaisCSHQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_K27vv2KPEe6SUplaisCSHQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K27vwGKPEe6SUplaisCSHQ" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_7fAFwGKaEe6Gj5K04qXrvQ" type="2007" element="_7c8QQGKaEe6Gj5K04qXrvQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_7fAs0GKaEe6Gj5K04qXrvQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_7fAs0WKaEe6Gj5K04qXrvQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_8EyTYGKaEe6Gj5K04qXrvQ" type="3007" element="_8ExFQGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_8EyTZWKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8EyTZmKaEe6Gj5K04qXrvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_delAQGK0Ee6hcJAWPaGpNw" type="3005" element="_deYzAGK0Ee6hcJAWPaGpNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_delAQmK0Ee6hcJAWPaGpNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_delAQWK0Ee6hcJAWPaGpNw" x="178" y="44" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jM51AGK0Ee6hcJAWPaGpNw" type="3008" element="_jM4m4GK0Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jM51AmK0Ee6hcJAWPaGpNw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jM51A2K0Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jM51AWK0Ee6hcJAWPaGpNw" x="374" y="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_p0748GK0Ee6hcJAWPaGpNw" type="3003" element="_p06q0GK0Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_p0748mK0Ee6hcJAWPaGpNw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_p07482K0Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p0748WK0Ee6hcJAWPaGpNw" x="662" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A0fk8GK1Ee6hcJAWPaGpNw" type="3005" element="_A0eW0GK1Ee6hcJAWPaGpNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_A0fk8mK1Ee6hcJAWPaGpNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A0fk8WK1Ee6hcJAWPaGpNw" x="323" y="162" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HNXLg2K1Ee6hcJAWPaGpNw" type="3008" element="_HNWkcGK1Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HNXLhWK1Ee6hcJAWPaGpNw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HNXykGK1Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HNXLhGK1Ee6hcJAWPaGpNw" x="522" y="177"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_No99AGK1Ee6hcJAWPaGpNw" type="3003" element="_No9V8GK1Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_No99AmK1Ee6hcJAWPaGpNw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_No99A2K1Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_No99AWK1Ee6hcJAWPaGpNw" x="758" y="184"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5yNYgGK1Ee6hcJAWPaGpNw" type="3005" element="_5yMKYGK1Ee6hcJAWPaGpNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5yNYgmK1Ee6hcJAWPaGpNw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="__3MyEGK7Ee6hcJAWPaGpNw" type="3043" element="__3E2QGK7Ee6hcJAWPaGpNw" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="__3NZIGK7Ee6hcJAWPaGpNw" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="__3NZIWK7Ee6hcJAWPaGpNw" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="__3MyEWK7Ee6hcJAWPaGpNw"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5yNYgWK1Ee6hcJAWPaGpNw" x="598" y="258" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MMc3g2K8Ee6hcJAWPaGpNw" type="3008" element="_MMcQcGK8Ee6hcJAWPaGpNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MMdekGK8Ee6hcJAWPaGpNw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MMdekWK8Ee6hcJAWPaGpNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MMc3hGK8Ee6hcJAWPaGpNw" x="782" y="269"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o9TJMGQbEe6w1fQx6ik-6g" type="3027" element="_o9SiIGQbEe6w1fQx6ik-6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o9TJMmQbEe6w1fQx6ik-6g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o9TJMWQbEe6w1fQx6ik-6g" x="458" y="56" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sgne8GQbEe6w1fQx6ik-6g" type="3027" element="_sgmQ0GQbEe6w1fQx6ik-6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sgne8mQbEe6w1fQx6ik-6g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sgne8WQbEe6w1fQx6ik-6g" x="593" y="164" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z6sq4GQbEe6w1fQx6ik-6g" type="3027" element="_z6sD0GQbEe6w1fQx6ik-6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z6sq4mQbEe6w1fQx6ik-6g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z6sq4WQbEe6w1fQx6ik-6g" x="662" y="426"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RzPQ0GQwEe6h_5UvdM1dDg" type="3012" element="_RzOpwGQwEe6h_5UvdM1dDg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_RzPQ0mQwEe6h_5UvdM1dDg" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RzPQ02QwEe6h_5UvdM1dDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RzPQ0WQwEe6h_5UvdM1dDg" x="62" y="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8EyTYWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8EyTYmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8EyTY2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8EyTZ2KaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8EyTZGKaEe6Gj5K04qXrvQ" x="53" y="10" width="1292" height="581"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_8XHZgGKaEe6Gj5K04qXrvQ" type="3007" element="_8XGycGKaEe6Gj5K04qXrvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_8XHZhWKaEe6Gj5K04qXrvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8XHZhmKaEe6Gj5K04qXrvQ" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8XHZgWKaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8XHZgmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8XHZg2KaEe6Gj5K04qXrvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8XIAkGKaEe6Gj5K04qXrvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8XHZhGKaEe6Gj5K04qXrvQ" x="257" y="179"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_7fAFwWKaEe6Gj5K04qXrvQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_7fAFwmKaEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_7fAFw2KaEe6Gj5K04qXrvQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_7fAs0mKaEe6Gj5K04qXrvQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7fAFxGKaEe6Gj5K04qXrvQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_K27vwWKPEe6SUplaisCSHQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_K27vwmKPEe6SUplaisCSHQ" type="4001" element="_K27vjGKPEe6SUplaisCSHQ" source="_K27vs2KPEe6SUplaisCSHQ" target="_K27vsGKPEe6SUplaisCSHQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K27vw2KPEe6SUplaisCSHQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K27vxGKPEe6SUplaisCSHQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K27vxWKPEe6SUplaisCSHQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K27vxmKPEe6SUplaisCSHQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2yvOIGKeEe6Gj5K04qXrvQ" type="4001" element="_2ytY8GKeEe6Gj5K04qXrvQ" source="_K27vsGKPEe6SUplaisCSHQ" target="_xlUHAGKeEe6Gj5K04qXrvQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2yv1MGKeEe6Gj5K04qXrvQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2yv1MWKeEe6Gj5K04qXrvQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2yvOIWKeEe6Gj5K04qXrvQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2yvOImKeEe6Gj5K04qXrvQ" points="[0, 9, -29, -248]$[6, 219, -23, -38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2yxqYGKeEe6Gj5K04qXrvQ" id="(0.48333333333333334,0.85)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XLUEsGKvEe6Jdd_cFX0v8A" type="4001" element="_XLQaUGKvEe6Jdd_cFX0v8A" source="_ngdIAGQsEe6h_5UvdM1dDg" target="_P3R2YGKvEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XLUrwGKvEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XLUrwWKvEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XLUEsWKvEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XLUEsmKvEe6Jdd_cFX0v8A" points="[3, 13, -169, -128]$[3, 109, -169, -32]$[118, 109, -54, -32]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZZDuoGKvEe6Jdd_cFX0v8A" id="(0.39166666666666666,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jLbAkmKvEe6Jdd_cFX0v8A" type="4001" element="_jLaZgGKvEe6Jdd_cFX0v8A" source="_P3R2YGKvEe6Jdd_cFX0v8A" target="_fD7mw2KvEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jLbnoGKvEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jLbnoWKvEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jLbAk2KvEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jLbAlGKvEe6Jdd_cFX0v8A" points="[1, -34, 1, 57]$[1, -106, 1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_M6fNwGKyEe6Jdd_cFX0v8A" id="(0.9855072463768116,0.5217391304347826)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TYdzQGKxEe6Jdd_cFX0v8A" type="4001" element="_TYdMMGKxEe6Jdd_cFX0v8A" source="_xlUHAGKeEe6Gj5K04qXrvQ" target="_5cGX4GKwEe6Jdd_cFX0v8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TYdzQ2KxEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TYdzRGKxEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TYdzQWKxEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TYdzQmKxEe6Jdd_cFX0v8A" points="[32, -7, -68, -4]$[98, -22, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TYfBYGKxEe6Jdd_cFX0v8A" id="(0.7935483870967742,0.5324675324675324)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GtgHEmKyEe6Jdd_cFX0v8A" type="4001" element="_GtfgAGKyEe6Jdd_cFX0v8A" source="_5cGX4GKwEe6Jdd_cFX0v8A" target="_K27vsGKPEe6SUplaisCSHQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GtgHFWKyEe6Jdd_cFX0v8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GtgHFmKyEe6Jdd_cFX0v8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GtgHE2KyEe6Jdd_cFX0v8A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GtgHFGKyEe6Jdd_cFX0v8A" points="[0, -21, 108, 179]$[0, -184, 108, 16]$[-85, -184, 23, 16]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GthVMGKyEe6Jdd_cFX0v8A" id="(0.8083333333333333,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kO0lAGK0Ee6hcJAWPaGpNw" type="4001" element="_kOzW4GK0Ee6hcJAWPaGpNw" source="_delAQGK0Ee6hcJAWPaGpNw" target="_jM51AGK0Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kO0lA2K0Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kO0lBGK0Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kO0lAWK0Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kO0lAmK0Ee6hcJAWPaGpNw" points="[30, -4, -69, -2]$[91, -15, -8, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kO1zIGK0Ee6hcJAWPaGpNw" id="(0.7972972972972973,0.5135135135135135)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FssqAGK1Ee6hcJAWPaGpNw" type="4001" element="_FskuMGK1Ee6hcJAWPaGpNw" source="_jM51AGK0Ee6hcJAWPaGpNw" target="_A0fk8GK1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FssqA2K1Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FssqBGK1Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FssqAWK1Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FssqAmK1Ee6hcJAWPaGpNw" points="[-1, 20, 0, -67]$[-2, 82, -1, -5]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FstREGK1Ee6hcJAWPaGpNw" id="(0.4863013698630137,0.0684931506849315)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JKdKUGK1Ee6hcJAWPaGpNw" type="4001" element="_JKcjQGK1Ee6hcJAWPaGpNw" source="_A0fk8GK1Ee6hcJAWPaGpNw" target="_HNXLg2K1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JKdKU2K1Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JKdKVGK1Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JKdKUWK1Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JKdKUmK1Ee6hcJAWPaGpNw" points="[9, -4, -74, -3]$[76, -15, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JKeYcGK1Ee6hcJAWPaGpNw" id="(0.9383561643835616,0.5068493150684932)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CvxwcGK2Ee6hcJAWPaGpNw" type="4001" element="_CvtfAGK2Ee6hcJAWPaGpNw" source="_HNXLg2K1Ee6hcJAWPaGpNw" target="_5yNYgGK1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Cvxwc2K2Ee6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CvxwdGK2Ee6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CvxwcWK2Ee6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CvxwcmK2Ee6hcJAWPaGpNw" points="[0, 22, -62, -69]$[0, 92, -62, 1]$[55, 92, -7, 1]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CvyXgGK2Ee6hcJAWPaGpNw" id="(0.05303030303030303,0.4696969696969697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hMnh0mLAEe6hcJAWPaGpNw" type="4001" element="_hMm6wGLAEe6hcJAWPaGpNw" source="_5yNYgGK1Ee6hcJAWPaGpNw" target="_MMc3g2K8Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hMnh1WLAEe6hcJAWPaGpNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hMnh1mLAEe6hcJAWPaGpNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hMnh02LAEe6hcJAWPaGpNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hMnh1GLAEe6hcJAWPaGpNw" points="[9, -3, -73, -2]$[78, -18, -4, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hMoI4GLAEe6hcJAWPaGpNw" id="(0.9318181818181818,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q4qCoGQbEe6w1fQx6ik-6g" type="4001" element="_q4jU8GQbEe6w1fQx6ik-6g" source="_jM51AGK0Ee6hcJAWPaGpNw" target="_o9TJMGQbEe6w1fQx6ik-6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q4qCo2QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q4qCpGQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q4qCoWQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q4qComQbEe6w1fQx6ik-6g" points="[14, -7, -135, -8]$[99, -7, -50, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rjLmUmQbEe6w1fQx6ik-6g" type="4001" element="_rjK_QGQbEe6w1fQx6ik-6g" source="_o9TJMGQbEe6w1fQx6ik-6g" target="_p0748GK0Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rjMNYGQbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rjMNYWQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rjLmU2QbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rjLmVGQbEe6w1fQx6ik-6g" points="[13, -3, -83, 0]$[81, -3, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rjM0cGQbEe6w1fQx6ik-6g" id="(0.87,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xIHOgGQbEe6w1fQx6ik-6g" type="4001" element="_xH9dgGQbEe6w1fQx6ik-6g" source="_HNXLg2K1Ee6hcJAWPaGpNw" target="_sgne8GQbEe6w1fQx6ik-6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xIHOg2QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xIHOhGQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xIHOgWQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xIHOgmQbEe6w1fQx6ik-6g" points="[20, 2, -55, 0]$[50, 2, -25, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xIIcoGQbEe6w1fQx6ik-6g" id="(0.17857142857142858,0.5142857142857142)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xuTr0GQbEe6w1fQx6ik-6g" type="4001" element="_xuTEwGQbEe6w1fQx6ik-6g" source="_sgne8GQbEe6w1fQx6ik-6g" target="_No99AGK1Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xuTr02QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xuTr1GQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xuTr0WQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xuTr0mQbEe6w1fQx6ik-6g" points="[9, 4, -40, 4]$[53, 14, 4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xuUS4GQbEe6w1fQx6ik-6g" id="(0.9357142857142857,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1X_IQGQbEe6w1fQx6ik-6g" type="4001" element="_1X96IGQbEe6w1fQx6ik-6g" source="__3MyEGK7Ee6hcJAWPaGpNw" target="_z6sq4GQbEe6w1fQx6ik-6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1X_IQ2QbEe6w1fQx6ik-6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1X_vUGQbEe6w1fQx6ik-6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1X_IQWQbEe6w1fQx6ik-6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1X_IQmQbEe6w1fQx6ik-6g" points="[-3, 10, -35, -119]$[-3, 119, -35, -10]$[21, 119, -11, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1YAWYGQbEe6w1fQx6ik-6g" id="(0.84,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1YAWYWQbEe6w1fQx6ik-6g" id="(0.11,0.68)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GeHLoGQwEe6h_5UvdM1dDg" type="4001" element="_GeCTIGQwEe6h_5UvdM1dDg" source="_5cGX4GKwEe6Jdd_cFX0v8A" target="_PJGl02QwEe6h_5UvdM1dDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GeHLo2QwEe6h_5UvdM1dDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GeHLpGQwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GeHLoWQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GeHLomQwEe6h_5UvdM1dDg" points="[21, 1, -90, 0]$[105, 1, -6, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GeIZwGQwEe6h_5UvdM1dDg" id="(0.2,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sj8VA2QwEe6h_5UvdM1dDg" type="4001" element="_Sj8VAGQwEe6h_5UvdM1dDg" source="_RzPQ0GQwEe6h_5UvdM1dDg" target="_delAQGK0Ee6hcJAWPaGpNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sj8VBmQwEe6h_5UvdM1dDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sj8VB2QwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sj8VBGQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sj8VBWQwEe6h_5UvdM1dDg" points="[14, -2, -101, 13]$[101, -17, -14, -2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Sj9jIGQwEe6h_5UvdM1dDg" id="(0.0945945945945946,0.40540540540540543)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bsFlQWQwEe6h_5UvdM1dDg" type="4002" element="_bsFlQGQwEe6h_5UvdM1dDg" source="_PJGl02QwEe6h_5UvdM1dDg" target="_RzPQ0GQwEe6h_5UvdM1dDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bsGMUGQwEe6h_5UvdM1dDg" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bsGMUWQwEe6h_5UvdM1dDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bsFlQmQwEe6h_5UvdM1dDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bsFlQ2QwEe6h_5UvdM1dDg" points="[14, -1, 494, -407]$[153, -1, 633, -407]$[153, 271, 633, -135]$[-480, 271, 0, -135]$[-480, 391, 0, -15]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
